const HANJA_DATA = [
  // 8급 — 숫자
  { id: 'hanja_001', char: '一', hun: '한', eum: '일', pinyin: 'yī',    grade: 8, strokes: 1,  example: '一月', example_meaning: '일월' },
  { id: 'hanja_002', char: '二', hun: '두', eum: '이', pinyin: 'èr',    grade: 8, strokes: 2,  example: '二月', example_meaning: '이월' },
  { id: 'hanja_003', char: '三', hun: '석', eum: '삼', pinyin: 'sān',   grade: 8, strokes: 3,  example: '三月', example_meaning: '삼월' },
  { id: 'hanja_004', char: '四', hun: '넉', eum: '사', pinyin: 'sì',    grade: 8, strokes: 5,  example: '四月', example_meaning: '사월' },
  { id: 'hanja_005', char: '五', hun: '다섯', eum: '오', pinyin: 'wǔ', grade: 8, strokes: 4,  example: '五月', example_meaning: '오월' },
  { id: 'hanja_006', char: '六', hun: '여섯', eum: '육', pinyin: 'liù', grade: 8, strokes: 4,  example: '六月', example_meaning: '유월' },
  { id: 'hanja_007', char: '七', hun: '일곱', eum: '칠', pinyin: 'qī', grade: 8, strokes: 2,  example: '七月', example_meaning: '칠월' },
  { id: 'hanja_008', char: '八', hun: '여덟', eum: '팔', pinyin: 'bā', grade: 8, strokes: 2,  example: '八月', example_meaning: '팔월' },
  { id: 'hanja_009', char: '九', hun: '아홉', eum: '구', pinyin: 'jiǔ', grade: 8, strokes: 2,  example: '九月', example_meaning: '구월' },
  { id: 'hanja_010', char: '十', hun: '열', eum: '십', pinyin: 'shí',  grade: 8, strokes: 2,  example: '十月', example_meaning: '시월' },
  // 8급 — 자연
  { id: 'hanja_011', char: '山', hun: '뫼', eum: '산', pinyin: 'shān',  grade: 8, strokes: 3,  example: '山水', example_meaning: '산수' },
  { id: 'hanja_012', char: '水', hun: '물', eum: '수', pinyin: 'shuǐ', grade: 8, strokes: 4,  example: '水力', example_meaning: '수력' },
  { id: 'hanja_013', char: '火', hun: '불', eum: '화', pinyin: 'huǒ',  grade: 8, strokes: 4,  example: '火山', example_meaning: '화산' },
  { id: 'hanja_014', char: '木', hun: '나무', eum: '목', pinyin: 'mù', grade: 8, strokes: 4,  example: '木手', example_meaning: '목수' },
  { id: 'hanja_015', char: '金', hun: '쇠', eum: '금', pinyin: 'jīn',  grade: 8, strokes: 8,  example: '金山', example_meaning: '금산' },
  { id: 'hanja_016', char: '土', hun: '흙', eum: '토', pinyin: 'tǔ',   grade: 8, strokes: 3,  example: '土地', example_meaning: '토지' },
  { id: 'hanja_017', char: '日', hun: '날', eum: '일', pinyin: 'rì',   grade: 8, strokes: 4,  example: '日月', example_meaning: '일월' },
  { id: 'hanja_018', char: '月', hun: '달', eum: '월', pinyin: 'yuè',  grade: 8, strokes: 4,  example: '月光', example_meaning: '월광' },
  { id: 'hanja_019', char: '天', hun: '하늘', eum: '천', pinyin: 'tiān', grade: 8, strokes: 4, example: '天下', example_meaning: '천하' },
  { id: 'hanja_020', char: '地', hun: '땅', eum: '지', pinyin: 'dì',   grade: 8, strokes: 6,  example: '地下', example_meaning: '지하' },
  // 8급 — 방향
  { id: 'hanja_021', char: '東', hun: '동녘', eum: '동', pinyin: 'dōng', grade: 8, strokes: 8, example: '東西', example_meaning: '동서' },
  { id: 'hanja_022', char: '西', hun: '서녘', eum: '서', pinyin: 'xī',  grade: 8, strokes: 6,  example: '東西', example_meaning: '동서' },
  { id: 'hanja_023', char: '南', hun: '남녘', eum: '남', pinyin: 'nán', grade: 8, strokes: 9,  example: '南北', example_meaning: '남북' },
  { id: 'hanja_024', char: '北', hun: '북녘', eum: '북', pinyin: 'běi', grade: 8, strokes: 5,  example: '南北', example_meaning: '남북' },
  // 8급 — 가족
  { id: 'hanja_025', char: '父', hun: '아비', eum: '부', pinyin: 'fù',   grade: 8, strokes: 4, example: '父母', example_meaning: '부모' },
  { id: 'hanja_026', char: '母', hun: '어미', eum: '모', pinyin: 'mǔ',   grade: 8, strokes: 5, example: '父母', example_meaning: '부모' },
  { id: 'hanja_027', char: '兄', hun: '형', eum: '형', pinyin: 'xiōng', grade: 8, strokes: 5,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_028', char: '弟', hun: '아우', eum: '제', pinyin: 'dì',  grade: 8, strokes: 7,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_029', char: '子', hun: '아들', eum: '자', pinyin: 'zǐ',  grade: 8, strokes: 3,  example: '子女', example_meaning: '자녀' },
  { id: 'hanja_030', char: '女', hun: '계집', eum: '녀', pinyin: 'nǚ',  grade: 8, strokes: 3,  example: '女子', example_meaning: '여자' },
  // 8급 — 학교·나라
  { id: 'hanja_031', char: '學', hun: '배울', eum: '학', pinyin: 'xué', grade: 8, strokes: 16, example: '學校', example_meaning: '학교' },
  { id: 'hanja_032', char: '校', hun: '학교', eum: '교', pinyin: 'xiào', grade: 8, strokes: 10, example: '學校', example_meaning: '학교' },
  { id: 'hanja_033', char: '國', hun: '나라', eum: '국', pinyin: 'guó', grade: 8, strokes: 11, example: '國土', example_meaning: '국토' },
  { id: 'hanja_034', char: '王', hun: '임금', eum: '왕', pinyin: 'wáng', grade: 8, strokes: 4, example: '王子', example_meaning: '왕자' },
  { id: 'hanja_035', char: '民', hun: '백성', eum: '민', pinyin: 'mín', grade: 8, strokes: 5,  example: '國民', example_meaning: '국민' },
  // 8급 — 신체·사람
  { id: 'hanja_036', char: '人', hun: '사람', eum: '인', pinyin: 'rén', grade: 8, strokes: 2,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_037', char: '口', hun: '입', eum: '구', pinyin: 'kǒu',   grade: 8, strokes: 3,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_038', char: '手', hun: '손', eum: '수', pinyin: 'shǒu',  grade: 8, strokes: 4,  example: '手足', example_meaning: '수족' },
  { id: 'hanja_039', char: '目', hun: '눈', eum: '목', pinyin: 'mù',   grade: 8, strokes: 5,  example: '目前', example_meaning: '목전' },
  { id: 'hanja_040', char: '耳', hun: '귀', eum: '이', pinyin: 'ěr',   grade: 8, strokes: 6,  example: '耳目', example_meaning: '이목' },
  // 8급 — 크기·위치
  { id: 'hanja_041', char: '大', hun: '큰', eum: '대', pinyin: 'dà',    grade: 8, strokes: 3,  example: '大小', example_meaning: '대소' },
  { id: 'hanja_042', char: '小', hun: '작을', eum: '소', pinyin: 'xiǎo', grade: 8, strokes: 3, example: '大小', example_meaning: '대소' },
  { id: 'hanja_043', char: '上', hun: '위', eum: '상', pinyin: 'shàng', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_044', char: '下', hun: '아래', eum: '하', pinyin: 'xià', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_045', char: '中', hun: '가운데', eum: '중', pinyin: 'zhōng', grade: 8, strokes: 4, example: '中間', example_meaning: '중간' },
  { id: 'hanja_046', char: '外', hun: '바깥', eum: '외', pinyin: 'wài', grade: 8, strokes: 5,  example: '外國', example_meaning: '외국' },
  { id: 'hanja_047', char: '內', hun: '안', eum: '내', pinyin: 'nèi',   grade: 8, strokes: 4,  example: '國內', example_meaning: '국내' },
  // 8급 — 시간·생명
  { id: 'hanja_048', char: '年', hun: '해', eum: '년', pinyin: 'nián',  grade: 8, strokes: 6,  example: '年月', example_meaning: '연월' },
  { id: 'hanja_049', char: '先', hun: '먼저', eum: '선', pinyin: 'xiān', grade: 8, strokes: 6, example: '先生', example_meaning: '선생' },
  { id: 'hanja_050', char: '生', hun: '날', eum: '생', pinyin: 'shēng', grade: 8, strokes: 5,  example: '先生', example_meaning: '선생' },
  // 8급 — 색·형용
  { id: 'hanja_051', char: '白', hun: '흰', eum: '백', pinyin: 'bái',   grade: 8, strokes: 5,  example: '白色', example_meaning: '백색' },
  { id: 'hanja_052', char: '靑', hun: '푸를', eum: '청', pinyin: 'qīng', grade: 8, strokes: 8, example: '靑年', example_meaning: '청년' },
  { id: 'hanja_053', char: '長', hun: '길', eum: '장', pinyin: 'cháng', grade: 8, strokes: 8,  example: '長短', example_meaning: '장단' },
  { id: 'hanja_054', char: '正', hun: '바를', eum: '정', pinyin: 'zhèng', grade: 8, strokes: 5, example: '正直', example_meaning: '정직' },
  // 7급 입문 (stage 6+)
  { id: 'hanja_055', char: '力', hun: '힘', eum: '력', pinyin: 'lì',    grade: 7, strokes: 2,  example: '力道', example_meaning: '역도' },
  { id: 'hanja_056', char: '文', hun: '글', eum: '문', pinyin: 'wén',   grade: 7, strokes: 4,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_057', char: '字', hun: '글자', eum: '자', pinyin: 'zì',  grade: 7, strokes: 6,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_058', char: '門', hun: '문', eum: '문', pinyin: 'mén',   grade: 7, strokes: 8,  example: '門前', example_meaning: '문전' },
  { id: 'hanja_059', char: '里', hun: '마을', eum: '리', pinyin: 'lǐ',  grade: 7, strokes: 7,  example: '里長', example_meaning: '이장' },
  { id: 'hanja_060', char: '花', hun: '꽃', eum: '화', pinyin: 'huā',   grade: 7, strokes: 7,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_061', char: '草', hun: '풀', eum: '초', pinyin: 'cǎo',   grade: 7, strokes: 9,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_062', char: '林', hun: '수풀', eum: '림', pinyin: 'lín', grade: 7, strokes: 8,  example: '山林', example_meaning: '산림' },
  { id: 'hanja_063', char: '江', hun: '강', eum: '강', pinyin: 'jiāng', grade: 7, strokes: 6,  example: '江山', example_meaning: '강산' },
  { id: 'hanja_064', char: '海', hun: '바다', eum: '해', pinyin: 'hǎi', grade: 7, strokes: 9,  example: '海外', example_meaning: '해외' },
  { id: 'hanja_065', char: '風', hun: '바람', eum: '풍', pinyin: 'fēng', grade: 7, strokes: 9, example: '風水', example_meaning: '풍수' },
  { id: 'hanja_066', char: '石', hun: '돌', eum: '석', pinyin: 'shí',   grade: 7, strokes: 5,  example: '石山', example_meaning: '석산' },
  { id: 'hanja_067', char: '心', hun: '마음', eum: '심', pinyin: 'xīn', grade: 7, strokes: 4,  example: '心中', example_meaning: '심중' },
  { id: 'hanja_068', char: '食', hun: '먹을', eum: '식', pinyin: 'shí', grade: 7, strokes: 9,  example: '食水', example_meaning: '식수' },
  { id: 'hanja_069', char: '道', hun: '길', eum: '도', pinyin: 'dào',   grade: 7, strokes: 12, example: '道路', example_meaning: '도로' },
  { id: 'hanja_070', char: '家', hun: '집', eum: '가', pinyin: 'jiā',   grade: 7, strokes: 10, example: '家門', example_meaning: '가문' },
  { id: 'hanja_071', char: '工', hun: '장인', eum: '공', pinyin: 'gōng', grade: 7, strokes: 3, example: '工人', example_meaning: '공인' },
  { id: 'hanja_072', char: '市', hun: '시장', eum: '시', pinyin: 'shì', grade: 7, strokes: 5,  example: '市場', example_meaning: '시장' },
  { id: 'hanja_073', char: '村', hun: '마을', eum: '촌', pinyin: 'cūn', grade: 7, strokes: 7,  example: '山村', example_meaning: '산촌' },
  { id: 'hanja_074', char: '空', hun: '빌', eum: '공', pinyin: 'kōng', grade: 7, strokes: 8,   example: '空中', example_meaning: '공중' },
  { id: 'hanja_075', char: '足', hun: '발', eum: '족', pinyin: 'zú',    grade: 7, strokes: 7,  example: '手足', example_meaning: '수족' },
  // 7급 추가
  { id: 'hanja_076', char: '間', hun: '사이', eum: '간', pinyin: 'jiān',  grade: 7, strokes: 12, example: '人間', example_meaning: '인간' },
  { id: 'hanja_077', char: '歌', hun: '노래', eum: '가', pinyin: 'gē',    grade: 7, strokes: 14, example: '歌手', example_meaning: '가수' },
  { id: 'hanja_078', char: '強', hun: '강할', eum: '강', pinyin: 'qiáng', grade: 7, strokes: 11, example: '強力', example_meaning: '강력' },
  { id: 'hanja_079', char: '高', hun: '높을', eum: '고', pinyin: 'gāo',   grade: 7, strokes: 10, example: '高山', example_meaning: '고산' },
  { id: 'hanja_080', char: '古', hun: '예', eum: '고', pinyin: 'gǔ',      grade: 7, strokes: 5,  example: '古典', example_meaning: '고전' },
  { id: 'hanja_081', char: '球', hun: '공', eum: '구', pinyin: 'qiú',     grade: 7, strokes: 11, example: '地球', example_meaning: '지구' },
  { id: 'hanja_082', char: '今', hun: '이제', eum: '금', pinyin: 'jīn',   grade: 7, strokes: 4,  example: '今日', example_meaning: '금일' },
  { id: 'hanja_083', char: '記', hun: '기록할', eum: '기', pinyin: 'jì',  grade: 7, strokes: 10, example: '日記', example_meaning: '일기' },
  { id: 'hanja_084', char: '旗', hun: '기', eum: '기', pinyin: 'qí',      grade: 7, strokes: 14, example: '國旗', example_meaning: '국기' },
  { id: 'hanja_085', char: '氣', hun: '기운', eum: '기', pinyin: 'qì',    grade: 7, strokes: 10, example: '空氣', example_meaning: '공기' },
  { id: 'hanja_086', char: '男', hun: '사내', eum: '남', pinyin: 'nán',   grade: 7, strokes: 7,  example: '男女', example_meaning: '남녀' },
  { id: 'hanja_087', char: '農', hun: '농사', eum: '농', pinyin: 'nóng',  grade: 7, strokes: 13, example: '農村', example_meaning: '농촌' },
  { id: 'hanja_088', char: '答', hun: '대답', eum: '답', pinyin: 'dá',    grade: 7, strokes: 12, example: '問答', example_meaning: '문답' },
  { id: 'hanja_089', char: '堂', hun: '집', eum: '당', pinyin: 'táng',    grade: 7, strokes: 11, example: '食堂', example_meaning: '식당' },
  { id: 'hanja_090', char: '代', hun: '대신할', eum: '대', pinyin: 'dài', grade: 7, strokes: 5,  example: '時代', example_meaning: '시대' },
  { id: 'hanja_091', char: '冬', hun: '겨울', eum: '동', pinyin: 'dōng',  grade: 7, strokes: 5,  example: '冬夏', example_meaning: '동하' },
  { id: 'hanja_092', char: '動', hun: '움직일', eum: '동', pinyin: 'dòng', grade: 7, strokes: 11, example: '運動', example_meaning: '운동' },
  { id: 'hanja_093', char: '童', hun: '아이', eum: '동', pinyin: 'tóng',  grade: 7, strokes: 12, example: '童話', example_meaning: '동화' },
  { id: 'hanja_094', char: '同', hun: '한가지', eum: '동', pinyin: 'tóng', grade: 7, strokes: 6, example: '同心', example_meaning: '동심' },
  { id: 'hanja_095', char: '讀', hun: '읽을', eum: '독', pinyin: 'dú',    grade: 7, strokes: 22, example: '讀書', example_meaning: '독서' },
  { id: 'hanja_096', char: '馬', hun: '말', eum: '마', pinyin: 'mǎ',      grade: 7, strokes: 10, example: '馬車', example_meaning: '마차' },
  { id: 'hanja_097', char: '面', hun: '낯', eum: '면', pinyin: 'miàn',    grade: 7, strokes: 9,  example: '面前', example_meaning: '면전' },
  { id: 'hanja_098', char: '命', hun: '목숨', eum: '명', pinyin: 'mìng',  grade: 7, strokes: 8,  example: '生命', example_meaning: '생명' },
  { id: 'hanja_099', char: '名', hun: '이름', eum: '명', pinyin: 'míng',  grade: 7, strokes: 6,  example: '名山', example_meaning: '명산' },
  { id: 'hanja_100', char: '明', hun: '밝을', eum: '명', pinyin: 'míng',  grade: 7, strokes: 8,  example: '明白', example_meaning: '명백' },
  { id: 'hanja_101', char: '問', hun: '물을', eum: '문', pinyin: 'wèn',   grade: 7, strokes: 11, example: '問答', example_meaning: '문답' },
  { id: 'hanja_102', char: '物', hun: '물건', eum: '물', pinyin: 'wù',    grade: 7, strokes: 8,  example: '動物', example_meaning: '동물' },
  { id: 'hanja_103', char: '方', hun: '모', eum: '방', pinyin: 'fāng',    grade: 7, strokes: 4,  example: '地方', example_meaning: '지방' },
  { id: 'hanja_104', char: '百', hun: '일백', eum: '백', pinyin: 'bǎi',   grade: 7, strokes: 6,  example: '百年', example_meaning: '백년' },
  { id: 'hanja_105', char: '夫', hun: '지아비', eum: '부', pinyin: 'fū',  grade: 7, strokes: 4,  example: '夫人', example_meaning: '부인' },
  { id: 'hanja_106', char: '分', hun: '나눌', eum: '분', pinyin: 'fēn',   grade: 7, strokes: 4,  example: '分數', example_meaning: '분수' },
  { id: 'hanja_107', char: '不', hun: '아닐', eum: '불', pinyin: 'bù',    grade: 7, strokes: 4,  example: '不正', example_meaning: '부정' },
  { id: 'hanja_108', char: '社', hun: '모일', eum: '사', pinyin: 'shè',   grade: 7, strokes: 8,  example: '社會', example_meaning: '사회' },
  { id: 'hanja_109', char: '事', hun: '일', eum: '사', pinyin: 'shì',     grade: 7, strokes: 8,  example: '事物', example_meaning: '사물' },
  { id: 'hanja_110', char: '算', hun: '셈할', eum: '산', pinyin: 'suàn',  grade: 7, strokes: 14, example: '算數', example_meaning: '산수' },
  { id: 'hanja_111', char: '色', hun: '빛', eum: '색', pinyin: 'sè',      grade: 7, strokes: 6,  example: '色紙', example_meaning: '색지' },
  { id: 'hanja_112', char: '書', hun: '글', eum: '서', pinyin: 'shū',     grade: 7, strokes: 10, example: '讀書', example_meaning: '독서' },
  { id: 'hanja_113', char: '姓', hun: '성', eum: '성', pinyin: 'xìng',    grade: 7, strokes: 8,  example: '姓名', example_meaning: '성명' },
  { id: 'hanja_114', char: '世', hun: '인간', eum: '세', pinyin: 'shì',   grade: 7, strokes: 5,  example: '世上', example_meaning: '세상' },
  { id: 'hanja_115', char: '少', hun: '적을', eum: '소', pinyin: 'shǎo',  grade: 7, strokes: 4,  example: '多少', example_meaning: '다소' },
  { id: 'hanja_116', char: '所', hun: '바', eum: '소', pinyin: 'suǒ',     grade: 7, strokes: 8,  example: '所有', example_meaning: '소유' },
  { id: 'hanja_117', char: '植', hun: '심을', eum: '식', pinyin: 'zhí',   grade: 7, strokes: 12, example: '植物', example_meaning: '식물' },
  { id: 'hanja_118', char: '室', hun: '집', eum: '실', pinyin: 'shì',     grade: 7, strokes: 9,  example: '室內', example_meaning: '실내' },
  { id: 'hanja_119', char: '安', hun: '편안할', eum: '안', pinyin: 'ān',  grade: 7, strokes: 6,  example: '安全', example_meaning: '안전' },
  { id: 'hanja_120', char: '語', hun: '말씀', eum: '어', pinyin: 'yǔ',    grade: 7, strokes: 14, example: '國語', example_meaning: '국어' },
  { id: 'hanja_121', char: '然', hun: '그럴', eum: '연', pinyin: 'rán',   grade: 7, strokes: 12, example: '自然', example_meaning: '자연' },
  { id: 'hanja_122', char: '用', hun: '쓸', eum: '용', pinyin: 'yòng',    grade: 7, strokes: 5,  example: '使用', example_meaning: '사용' },
  { id: 'hanja_123', char: '牛', hun: '소', eum: '우', pinyin: 'niú',     grade: 7, strokes: 4,  example: '牛馬', example_meaning: '우마' },
  { id: 'hanja_124', char: '有', hun: '있을', eum: '유', pinyin: 'yǒu',   grade: 7, strokes: 6,  example: '有名', example_meaning: '유명' },
  { id: 'hanja_125', char: '育', hun: '기를', eum: '육', pinyin: 'yù',    grade: 7, strokes: 8,  example: '敎育', example_meaning: '교육' },
  { id: 'hanja_126', char: '音', hun: '소리', eum: '음', pinyin: 'yīn',   grade: 7, strokes: 9,  example: '音樂', example_meaning: '음악' },
  { id: 'hanja_127', char: '銀', hun: '은', eum: '은', pinyin: 'yín',     grade: 7, strokes: 14, example: '銀行', example_meaning: '은행' },
  { id: 'hanja_128', char: '入', hun: '들', eum: '입', pinyin: 'rù',      grade: 7, strokes: 2,  example: '入口', example_meaning: '입구' },
  { id: 'hanja_129', char: '作', hun: '지을', eum: '작', pinyin: 'zuò',   grade: 7, strokes: 7,  example: '作文', example_meaning: '작문' },
  { id: 'hanja_130', char: '場', hun: '마당', eum: '장', pinyin: 'chǎng', grade: 7, strokes: 12, example: '市場', example_meaning: '시장' },
  { id: 'hanja_131', char: '全', hun: '온전할', eum: '전', pinyin: 'quán', grade: 7, strokes: 6, example: '全國', example_meaning: '전국' },
  { id: 'hanja_132', char: '電', hun: '번개', eum: '전', pinyin: 'diàn',  grade: 7, strokes: 13, example: '電氣', example_meaning: '전기' },
  { id: 'hanja_133', char: '前', hun: '앞', eum: '전', pinyin: 'qián',    grade: 7, strokes: 9,  example: '前後', example_meaning: '전후' },
  { id: 'hanja_134', char: '祖', hun: '할아비', eum: '조', pinyin: 'zǔ',  grade: 7, strokes: 10, example: '祖國', example_meaning: '조국' },
  { id: 'hanja_135', char: '紙', hun: '종이', eum: '지', pinyin: 'zhǐ',   grade: 7, strokes: 10, example: '色紙', example_meaning: '색지' },
  { id: 'hanja_136', char: '直', hun: '곧을', eum: '직', pinyin: 'zhí',   grade: 7, strokes: 8,  example: '正直', example_meaning: '정직' },
  { id: 'hanja_137', char: '千', hun: '일천', eum: '천', pinyin: 'qiān',  grade: 7, strokes: 3,  example: '千萬', example_meaning: '천만' },
  { id: 'hanja_138', char: '川', hun: '내', eum: '천', pinyin: 'chuān',   grade: 7, strokes: 3,  example: '山川', example_meaning: '산천' },
  { id: 'hanja_139', char: '春', hun: '봄', eum: '춘', pinyin: 'chūn',    grade: 7, strokes: 9,  example: '春秋', example_meaning: '춘추' },
  { id: 'hanja_140', char: '親', hun: '친할', eum: '친', pinyin: 'qīn',   grade: 7, strokes: 16, example: '親舊', example_meaning: '친구' },
  { id: 'hanja_141', char: '他', hun: '다를', eum: '타', pinyin: 'tā',    grade: 7, strokes: 5,  example: '他人', example_meaning: '타인' },
  { id: 'hanja_142', char: '太', hun: '클', eum: '태', pinyin: 'tài',     grade: 7, strokes: 4,  example: '太陽', example_meaning: '태양' },
  { id: 'hanja_143', char: '通', hun: '통할', eum: '통', pinyin: 'tōng',  grade: 7, strokes: 11, example: '交通', example_meaning: '교통' },
  { id: 'hanja_144', char: '平', hun: '평평할', eum: '평', pinyin: 'píng', grade: 7, strokes: 5, example: '平和', example_meaning: '평화' },
  { id: 'hanja_145', char: '韓', hun: '한국', eum: '한', pinyin: 'hán',   grade: 7, strokes: 17, example: '韓國', example_meaning: '한국' },
  { id: 'hanja_146', char: '漢', hun: '한수', eum: '한', pinyin: 'hàn',   grade: 7, strokes: 14, example: '漢字', example_meaning: '한자' },
  { id: 'hanja_147', char: '話', hun: '말씀', eum: '화', pinyin: 'huà',   grade: 7, strokes: 13, example: '電話', example_meaning: '전화' },
  { id: 'hanja_148', char: '黃', hun: '누를', eum: '황', pinyin: 'huáng', grade: 7, strokes: 11, example: '黃金', example_meaning: '황금' },
  { id: 'hanja_149', char: '後', hun: '뒤', eum: '후', pinyin: 'hòu',     grade: 7, strokes: 9,  example: '前後', example_meaning: '전후' },
  { id: 'hanja_150', char: '休', hun: '쉴', eum: '휴', pinyin: 'xiū',     grade: 7, strokes: 6,  example: '休日', example_meaning: '휴일' },
  { id: 'hanja_151', char: '夏', hun: '여름', eum: '하', pinyin: 'xià',   grade: 7, strokes: 10, example: '夏冬', example_meaning: '하동' },
  { id: 'hanja_152', char: '秋', hun: '가을', eum: '추', pinyin: 'qiū',   grade: 7, strokes: 9,  example: '春秋', example_meaning: '춘추' },
  { id: 'hanja_153', char: '元', hun: '으뜸', eum: '원', pinyin: 'yuán',  grade: 7, strokes: 4,  example: '元氣', example_meaning: '원기' },
];

const STAGES = [
  { id: 1, grade: 8, words: ['hanja_001','hanja_002','hanja_003','hanja_004','hanja_005','hanja_006','hanja_007','hanja_008','hanja_009','hanja_010'] },
  { id: 2, grade: 8, words: ['hanja_011','hanja_012','hanja_013','hanja_014','hanja_015','hanja_016','hanja_017','hanja_018','hanja_019','hanja_020'] },
  { id: 3, grade: 8, words: ['hanja_021','hanja_022','hanja_023','hanja_024','hanja_025','hanja_026','hanja_027','hanja_028','hanja_029','hanja_030'] },
  { id: 4, grade: 8, words: ['hanja_031','hanja_032','hanja_033','hanja_034','hanja_035','hanja_036','hanja_037','hanja_038','hanja_039','hanja_040'] },
  { id: 5, grade: 8, words: ['hanja_041','hanja_042','hanja_043','hanja_044','hanja_045','hanja_046','hanja_047','hanja_048','hanja_049','hanja_050'] },
  { id: 6, grade: 8, words: ['hanja_051','hanja_052','hanja_053','hanja_054','hanja_055','hanja_056','hanja_057','hanja_058','hanja_059','hanja_060'] },
  { id: 7, grade: 7, words: ['hanja_061','hanja_062','hanja_063','hanja_064','hanja_065','hanja_066','hanja_067','hanja_068','hanja_069','hanja_070'] },
  { id: 8,  grade: 7, words: ['hanja_071','hanja_072','hanja_073','hanja_074','hanja_075','hanja_076','hanja_077','hanja_078','hanja_079','hanja_080'] },
  { id: 9,  grade: 7, words: ['hanja_081','hanja_082','hanja_083','hanja_084','hanja_085','hanja_086','hanja_087','hanja_088','hanja_089','hanja_090'] },
  { id: 10, grade: 7, words: ['hanja_091','hanja_092','hanja_093','hanja_094','hanja_095','hanja_096','hanja_097','hanja_098','hanja_099','hanja_100'] },
  { id: 11, grade: 7, words: ['hanja_101','hanja_102','hanja_103','hanja_104','hanja_105','hanja_106','hanja_107','hanja_108','hanja_109','hanja_110'] },
  { id: 12, grade: 7, words: ['hanja_111','hanja_112','hanja_113','hanja_114','hanja_115','hanja_116','hanja_117','hanja_118','hanja_119','hanja_120'] },
  { id: 13, grade: 7, words: ['hanja_121','hanja_122','hanja_123','hanja_124','hanja_125','hanja_126','hanja_127','hanja_128','hanja_129','hanja_130'] },
  { id: 14, grade: 7, words: ['hanja_131','hanja_132','hanja_133','hanja_134','hanja_135','hanja_136','hanja_137','hanja_138','hanja_139','hanja_140'] },
  { id: 15, grade: 7, words: ['hanja_141','hanja_142','hanja_143','hanja_144','hanja_145','hanja_146','hanja_147','hanja_148','hanja_149','hanja_150'] },
  { id: 16, grade: 7, words: ['hanja_151','hanja_152','hanja_153','hanja_076','hanja_086','hanja_096','hanja_106','hanja_116','hanja_126','hanja_136'] },
];
