const HANJA_DATA = [
  // 8급 — 숫자
  { id: 'hanja_001', char: '一', hun: '한', eum: '일', pinyin: 'yī',    grade: 8, strokes: 1,  example: '一月', example_meaning: '일월' },
  { id: 'hanja_002', char: '二', hun: '두', eum: '이', pinyin: 'èr',    grade: 8, strokes: 2,  example: '二月', example_meaning: '이월' },
  { id: 'hanja_003', char: '三', hun: '석', eum: '삼', pinyin: 'sān',   grade: 8, strokes: 3,  example: '三月', example_meaning: '삼월' },
  { id: 'hanja_004', char: '四', hun: '넉', eum: '사', pinyin: 'sì',    grade: 8, strokes: 5,  example: '四月', example_meaning: '사월' },
  { id: 'hanja_005', char: '五', hun: '다섯', eum: '오', pinyin: 'wǔ', grade: 8, strokes: 4,  example: '五月', example_meaning: '오월' },
  { id: 'hanja_006', char: '六', hun: '여섯', eum: '육', pinyin: 'liù', grade: 8, strokes: 4,  example: '六月', example_meaning: '유월' },
  { id: 'hanja_007', char: '七', hun: '일곱', eum: '칠', pinyin: 'qī', grade: 8, strokes: 2,  example: '七月', example_meaning: '칠월' },
  { id: 'hanja_008', char: '八', hun: '여덟', eum: '팔', pinyin: 'bā', grade: 8, strokes: 2,  example: '八月', example_meaning: '팔월' },
  { id: 'hanja_009', char: '九', hun: '아홉', eum: '구', pinyin: 'jiǔ', grade: 8, strokes: 2,  example: '九月', example_meaning: '구월' },
  { id: 'hanja_010', char: '十', hun: '열', eum: '십', pinyin: 'shí',  grade: 8, strokes: 2,  example: '十月', example_meaning: '시월' },
  // 8급 — 자연
  { id: 'hanja_011', char: '山', hun: '뫼', eum: '산', pinyin: 'shān',  grade: 8, strokes: 3,  example: '山水', example_meaning: '산수' },
  { id: 'hanja_012', char: '水', hun: '물', eum: '수', pinyin: 'shuǐ', grade: 8, strokes: 4,  example: '水力', example_meaning: '수력' },
  { id: 'hanja_013', char: '火', hun: '불', eum: '화', pinyin: 'huǒ',  grade: 8, strokes: 4,  example: '火山', example_meaning: '화산' },
  { id: 'hanja_014', char: '木', hun: '나무', eum: '목', pinyin: 'mù', grade: 8, strokes: 4,  example: '木手', example_meaning: '목수' },
  { id: 'hanja_015', char: '金', hun: '쇠', eum: '금', pinyin: 'jīn',  grade: 8, strokes: 8,  example: '金山', example_meaning: '금산' },
  { id: 'hanja_016', char: '土', hun: '흙', eum: '토', pinyin: 'tǔ',   grade: 8, strokes: 3,  example: '土地', example_meaning: '토지' },
  { id: 'hanja_017', char: '日', hun: '날', eum: '일', pinyin: 'rì',   grade: 8, strokes: 4,  example: '日月', example_meaning: '일월' },
  { id: 'hanja_018', char: '月', hun: '달', eum: '월', pinyin: 'yuè',  grade: 8, strokes: 4,  example: '月光', example_meaning: '월광' },
  { id: 'hanja_019', char: '天', hun: '하늘', eum: '천', pinyin: 'tiān', grade: 8, strokes: 4, example: '天下', example_meaning: '천하' },
  { id: 'hanja_020', char: '地', hun: '땅', eum: '지', pinyin: 'dì',   grade: 8, strokes: 6,  example: '地下', example_meaning: '지하' },
  // 8급 — 방향
  { id: 'hanja_021', char: '東', hun: '동녘', eum: '동', pinyin: 'dōng', grade: 8, strokes: 8, example: '東西', example_meaning: '동서' },
  { id: 'hanja_022', char: '西', hun: '서녘', eum: '서', pinyin: 'xī',  grade: 8, strokes: 6,  example: '東西', example_meaning: '동서' },
  { id: 'hanja_023', char: '南', hun: '남녘', eum: '남', pinyin: 'nán', grade: 8, strokes: 9,  example: '南北', example_meaning: '남북' },
  { id: 'hanja_024', char: '北', hun: '북녘', eum: '북', pinyin: 'běi', grade: 8, strokes: 5,  example: '南北', example_meaning: '남북' },
  // 8급 — 가족
  { id: 'hanja_025', char: '父', hun: '아비', eum: '부', pinyin: 'fù',   grade: 8, strokes: 4, example: '父母', example_meaning: '부모' },
  { id: 'hanja_026', char: '母', hun: '어미', eum: '모', pinyin: 'mǔ',   grade: 8, strokes: 5, example: '父母', example_meaning: '부모' },
  { id: 'hanja_027', char: '兄', hun: '형', eum: '형', pinyin: 'xiōng', grade: 8, strokes: 5,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_028', char: '弟', hun: '아우', eum: '제', pinyin: 'dì',  grade: 8, strokes: 7,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_029', char: '子', hun: '아들', eum: '자', pinyin: 'zǐ',  grade: 8, strokes: 3,  example: '子女', example_meaning: '자녀' },
  { id: 'hanja_030', char: '女', hun: '계집', eum: '녀', pinyin: 'nǚ',  grade: 8, strokes: 3,  example: '女子', example_meaning: '여자' },
  // 8급 — 학교·나라
  { id: 'hanja_031', char: '學', hun: '배울', eum: '학', pinyin: 'xué', grade: 8, strokes: 16, example: '學校', example_meaning: '학교' },
  { id: 'hanja_032', char: '校', hun: '학교', eum: '교', pinyin: 'xiào', grade: 8, strokes: 10, example: '學校', example_meaning: '학교' },
  { id: 'hanja_033', char: '國', hun: '나라', eum: '국', pinyin: 'guó', grade: 8, strokes: 11, example: '國土', example_meaning: '국토' },
  { id: 'hanja_034', char: '王', hun: '임금', eum: '왕', pinyin: 'wáng', grade: 8, strokes: 4, example: '王子', example_meaning: '왕자' },
  { id: 'hanja_035', char: '民', hun: '백성', eum: '민', pinyin: 'mín', grade: 8, strokes: 5,  example: '國民', example_meaning: '국민' },
  // 8급 — 신체·사람
  { id: 'hanja_036', char: '人', hun: '사람', eum: '인', pinyin: 'rén', grade: 8, strokes: 2,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_037', char: '口', hun: '입', eum: '구', pinyin: 'kǒu',   grade: 8, strokes: 3,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_038', char: '手', hun: '손', eum: '수', pinyin: 'shǒu',  grade: 8, strokes: 4,  example: '手足', example_meaning: '수족' },
  { id: 'hanja_039', char: '目', hun: '눈', eum: '목', pinyin: 'mù',   grade: 8, strokes: 5,  example: '目前', example_meaning: '목전' },
  { id: 'hanja_040', char: '耳', hun: '귀', eum: '이', pinyin: 'ěr',   grade: 8, strokes: 6,  example: '耳目', example_meaning: '이목' },
  // 8급 — 크기·위치
  { id: 'hanja_041', char: '大', hun: '큰', eum: '대', pinyin: 'dà',    grade: 8, strokes: 3,  example: '大小', example_meaning: '대소' },
  { id: 'hanja_042', char: '小', hun: '작을', eum: '소', pinyin: 'xiǎo', grade: 8, strokes: 3, example: '大小', example_meaning: '대소' },
  { id: 'hanja_043', char: '上', hun: '위', eum: '상', pinyin: 'shàng', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_044', char: '下', hun: '아래', eum: '하', pinyin: 'xià', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_045', char: '中', hun: '가운데', eum: '중', pinyin: 'zhōng', grade: 8, strokes: 4, example: '中間', example_meaning: '중간' },
  { id: 'hanja_046', char: '外', hun: '바깥', eum: '외', pinyin: 'wài', grade: 8, strokes: 5,  example: '外國', example_meaning: '외국' },
  { id: 'hanja_047', char: '內', hun: '안', eum: '내', pinyin: 'nèi',   grade: 8, strokes: 4,  example: '國內', example_meaning: '국내' },
  // 8급 — 시간·생명
  { id: 'hanja_048', char: '年', hun: '해', eum: '년', pinyin: 'nián',  grade: 8, strokes: 6,  example: '年月', example_meaning: '연월' },
  { id: 'hanja_049', char: '先', hun: '먼저', eum: '선', pinyin: 'xiān', grade: 8, strokes: 6, example: '先生', example_meaning: '선생' },
  { id: 'hanja_050', char: '生', hun: '날', eum: '생', pinyin: 'shēng', grade: 8, strokes: 5,  example: '先生', example_meaning: '선생' },
  // 8급 — 색·형용
  { id: 'hanja_051', char: '白', hun: '흰', eum: '백', pinyin: 'bái',   grade: 8, strokes: 5,  example: '白色', example_meaning: '백색' },
  { id: 'hanja_052', char: '靑', hun: '푸를', eum: '청', pinyin: 'qīng', grade: 8, strokes: 8, example: '靑年', example_meaning: '청년' },
  { id: 'hanja_053', char: '長', hun: '길', eum: '장', pinyin: 'cháng', grade: 8, strokes: 8,  example: '長短', example_meaning: '장단' },
  { id: 'hanja_054', char: '正', hun: '바를', eum: '정', pinyin: 'zhèng', grade: 8, strokes: 5, example: '正直', example_meaning: '정직' },
  // 7급 입문 (stage 6+)
  { id: 'hanja_055', char: '力', hun: '힘', eum: '력', pinyin: 'lì',    grade: 7, strokes: 2,  example: '力道', example_meaning: '역도' },
  { id: 'hanja_056', char: '文', hun: '글', eum: '문', pinyin: 'wén',   grade: 7, strokes: 4,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_057', char: '字', hun: '글자', eum: '자', pinyin: 'zì',  grade: 7, strokes: 6,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_058', char: '門', hun: '문', eum: '문', pinyin: 'mén',   grade: 7, strokes: 8,  example: '門前', example_meaning: '문전' },
  { id: 'hanja_059', char: '里', hun: '마을', eum: '리', pinyin: 'lǐ',  grade: 7, strokes: 7,  example: '里長', example_meaning: '이장' },
  { id: 'hanja_060', char: '花', hun: '꽃', eum: '화', pinyin: 'huā',   grade: 7, strokes: 7,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_061', char: '草', hun: '풀', eum: '초', pinyin: 'cǎo',   grade: 7, strokes: 9,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_062', char: '林', hun: '수풀', eum: '림', pinyin: 'lín', grade: 7, strokes: 8,  example: '山林', example_meaning: '산림' },
  { id: 'hanja_063', char: '江', hun: '강', eum: '강', pinyin: 'jiāng', grade: 7, strokes: 6,  example: '江山', example_meaning: '강산' },
  { id: 'hanja_064', char: '海', hun: '바다', eum: '해', pinyin: 'hǎi', grade: 7, strokes: 9,  example: '海外', example_meaning: '해외' },
  { id: 'hanja_065', char: '風', hun: '바람', eum: '풍', pinyin: 'fēng', grade: 7, strokes: 9, example: '風水', example_meaning: '풍수' },
  { id: 'hanja_066', char: '石', hun: '돌', eum: '석', pinyin: 'shí',   grade: 7, strokes: 5,  example: '石山', example_meaning: '석산' },
  { id: 'hanja_067', char: '心', hun: '마음', eum: '심', pinyin: 'xīn', grade: 7, strokes: 4,  example: '心中', example_meaning: '심중' },
  { id: 'hanja_068', char: '食', hun: '먹을', eum: '식', pinyin: 'shí', grade: 7, strokes: 9,  example: '食水', example_meaning: '식수' },
  { id: 'hanja_069', char: '道', hun: '길', eum: '도', pinyin: 'dào',   grade: 7, strokes: 12, example: '道路', example_meaning: '도로' },
  { id: 'hanja_070', char: '家', hun: '집', eum: '가', pinyin: 'jiā',   grade: 7, strokes: 10, example: '家門', example_meaning: '가문' },
  { id: 'hanja_071', char: '工', hun: '장인', eum: '공', pinyin: 'gōng', grade: 7, strokes: 3, example: '工人', example_meaning: '공인' },
  { id: 'hanja_072', char: '市', hun: '시장', eum: '시', pinyin: 'shì', grade: 7, strokes: 5,  example: '市場', example_meaning: '시장' },
  { id: 'hanja_073', char: '村', hun: '마을', eum: '촌', pinyin: 'cūn', grade: 7, strokes: 7,  example: '山村', example_meaning: '산촌' },
  { id: 'hanja_074', char: '空', hun: '빌', eum: '공', pinyin: 'kōng', grade: 7, strokes: 8,   example: '空中', example_meaning: '공중' },
  { id: 'hanja_075', char: '足', hun: '발', eum: '족', pinyin: 'zú',    grade: 7, strokes: 7,  example: '手足', example_meaning: '수족' },
  // 7급 추가
  { id: 'hanja_076', char: '間', hun: '사이', eum: '간', pinyin: 'jiān',  grade: 7, strokes: 12, example: '人間', example_meaning: '인간' },
  { id: 'hanja_077', char: '歌', hun: '노래', eum: '가', pinyin: 'gē',    grade: 7, strokes: 14, example: '歌手', example_meaning: '가수' },
  { id: 'hanja_078', char: '強', hun: '강할', eum: '강', pinyin: 'qiáng', grade: 7, strokes: 11, example: '強力', example_meaning: '강력' },
  { id: 'hanja_079', char: '高', hun: '높을', eum: '고', pinyin: 'gāo',   grade: 7, strokes: 10, example: '高山', example_meaning: '고산' },
  { id: 'hanja_080', char: '古', hun: '예', eum: '고', pinyin: 'gǔ',      grade: 7, strokes: 5,  example: '古典', example_meaning: '고전' },
  { id: 'hanja_081', char: '球', hun: '공', eum: '구', pinyin: 'qiú',     grade: 7, strokes: 11, example: '地球', example_meaning: '지구' },
  { id: 'hanja_082', char: '今', hun: '이제', eum: '금', pinyin: 'jīn',   grade: 7, strokes: 4,  example: '今日', example_meaning: '금일' },
  { id: 'hanja_083', char: '記', hun: '기록할', eum: '기', pinyin: 'jì',  grade: 7, strokes: 10, example: '日記', example_meaning: '일기' },
  { id: 'hanja_084', char: '旗', hun: '기', eum: '기', pinyin: 'qí',      grade: 7, strokes: 14, example: '國旗', example_meaning: '국기' },
  { id: 'hanja_085', char: '氣', hun: '기운', eum: '기', pinyin: 'qì',    grade: 7, strokes: 10, example: '空氣', example_meaning: '공기' },
  { id: 'hanja_086', char: '男', hun: '사내', eum: '남', pinyin: 'nán',   grade: 7, strokes: 7,  example: '男女', example_meaning: '남녀' },
  { id: 'hanja_087', char: '農', hun: '농사', eum: '농', pinyin: 'nóng',  grade: 7, strokes: 13, example: '農村', example_meaning: '농촌' },
  { id: 'hanja_088', char: '答', hun: '대답', eum: '답', pinyin: 'dá',    grade: 7, strokes: 12, example: '問答', example_meaning: '문답' },
  { id: 'hanja_089', char: '堂', hun: '집', eum: '당', pinyin: 'táng',    grade: 7, strokes: 11, example: '食堂', example_meaning: '식당' },
  { id: 'hanja_090', char: '代', hun: '대신할', eum: '대', pinyin: 'dài', grade: 7, strokes: 5,  example: '時代', example_meaning: '시대' },
  { id: 'hanja_091', char: '冬', hun: '겨울', eum: '동', pinyin: 'dōng',  grade: 7, strokes: 5,  example: '冬夏', example_meaning: '동하' },
  { id: 'hanja_092', char: '動', hun: '움직일', eum: '동', pinyin: 'dòng', grade: 7, strokes: 11, example: '運動', example_meaning: '운동' },
  { id: 'hanja_093', char: '童', hun: '아이', eum: '동', pinyin: 'tóng',  grade: 7, strokes: 12, example: '童話', example_meaning: '동화' },
  { id: 'hanja_094', char: '同', hun: '한가지', eum: '동', pinyin: 'tóng', grade: 7, strokes: 6, example: '同心', example_meaning: '동심' },
  { id: 'hanja_095', char: '讀', hun: '읽을', eum: '독', pinyin: 'dú',    grade: 7, strokes: 22, example: '讀書', example_meaning: '독서' },
  { id: 'hanja_096', char: '馬', hun: '말', eum: '마', pinyin: 'mǎ',      grade: 7, strokes: 10, example: '馬車', example_meaning: '마차' },
  { id: 'hanja_097', char: '面', hun: '낯', eum: '면', pinyin: 'miàn',    grade: 7, strokes: 9,  example: '面前', example_meaning: '면전' },
  { id: 'hanja_098', char: '命', hun: '목숨', eum: '명', pinyin: 'mìng',  grade: 7, strokes: 8,  example: '生命', example_meaning: '생명' },
  { id: 'hanja_099', char: '名', hun: '이름', eum: '명', pinyin: 'míng',  grade: 7, strokes: 6,  example: '名山', example_meaning: '명산' },
  { id: 'hanja_100', char: '明', hun: '밝을', eum: '명', pinyin: 'míng',  grade: 7, strokes: 8,  example: '明白', example_meaning: '명백' },
  { id: 'hanja_101', char: '問', hun: '물을', eum: '문', pinyin: 'wèn',   grade: 7, strokes: 11, example: '問答', example_meaning: '문답' },
  { id: 'hanja_102', char: '物', hun: '물건', eum: '물', pinyin: 'wù',    grade: 7, strokes: 8,  example: '動物', example_meaning: '동물' },
  { id: 'hanja_103', char: '方', hun: '모', eum: '방', pinyin: 'fāng',    grade: 7, strokes: 4,  example: '地方', example_meaning: '지방' },
  { id: 'hanja_104', char: '百', hun: '일백', eum: '백', pinyin: 'bǎi',   grade: 7, strokes: 6,  example: '百年', example_meaning: '백년' },
  { id: 'hanja_105', char: '夫', hun: '지아비', eum: '부', pinyin: 'fū',  grade: 7, strokes: 4,  example: '夫人', example_meaning: '부인' },
  { id: 'hanja_106', char: '分', hun: '나눌', eum: '분', pinyin: 'fēn',   grade: 7, strokes: 4,  example: '分數', example_meaning: '분수' },
  { id: 'hanja_107', char: '不', hun: '아닐', eum: '불', pinyin: 'bù',    grade: 7, strokes: 4,  example: '不正', example_meaning: '부정' },
  { id: 'hanja_108', char: '社', hun: '모일', eum: '사', pinyin: 'shè',   grade: 7, strokes: 8,  example: '社會', example_meaning: '사회' },
  { id: 'hanja_109', char: '事', hun: '일', eum: '사', pinyin: 'shì',     grade: 7, strokes: 8,  example: '事物', example_meaning: '사물' },
  { id: 'hanja_110', char: '算', hun: '셈할', eum: '산', pinyin: 'suàn',  grade: 7, strokes: 14, example: '算數', example_meaning: '산수' },
  { id: 'hanja_111', char: '色', hun: '빛', eum: '색', pinyin: 'sè',      grade: 7, strokes: 6,  example: '色紙', example_meaning: '색지' },
  { id: 'hanja_112', char: '書', hun: '글', eum: '서', pinyin: 'shū',     grade: 7, strokes: 10, example: '讀書', example_meaning: '독서' },
  { id: 'hanja_113', char: '姓', hun: '성', eum: '성', pinyin: 'xìng',    grade: 7, strokes: 8,  example: '姓名', example_meaning: '성명' },
  { id: 'hanja_114', char: '世', hun: '인간', eum: '세', pinyin: 'shì',   grade: 7, strokes: 5,  example: '世上', example_meaning: '세상' },
  { id: 'hanja_115', char: '少', hun: '적을', eum: '소', pinyin: 'shǎo',  grade: 7, strokes: 4,  example: '多少', example_meaning: '다소' },
  { id: 'hanja_116', char: '所', hun: '바', eum: '소', pinyin: 'suǒ',     grade: 7, strokes: 8,  example: '所有', example_meaning: '소유' },
  { id: 'hanja_117', char: '植', hun: '심을', eum: '식', pinyin: 'zhí',   grade: 7, strokes: 12, example: '植物', example_meaning: '식물' },
  { id: 'hanja_118', char: '室', hun: '집', eum: '실', pinyin: 'shì',     grade: 7, strokes: 9,  example: '室內', example_meaning: '실내' },
  { id: 'hanja_119', char: '安', hun: '편안할', eum: '안', pinyin: 'ān',  grade: 7, strokes: 6,  example: '安全', example_meaning: '안전' },
  { id: 'hanja_120', char: '語', hun: '말씀', eum: '어', pinyin: 'yǔ',    grade: 7, strokes: 14, example: '國語', example_meaning: '국어' },
  { id: 'hanja_121', char: '然', hun: '그럴', eum: '연', pinyin: 'rán',   grade: 7, strokes: 12, example: '自然', example_meaning: '자연' },
  { id: 'hanja_122', char: '用', hun: '쓸', eum: '용', pinyin: 'yòng',    grade: 7, strokes: 5,  example: '使用', example_meaning: '사용' },
  { id: 'hanja_123', char: '牛', hun: '소', eum: '우', pinyin: 'niú',     grade: 7, strokes: 4,  example: '牛馬', example_meaning: '우마' },
  { id: 'hanja_124', char: '有', hun: '있을', eum: '유', pinyin: 'yǒu',   grade: 7, strokes: 6,  example: '有名', example_meaning: '유명' },
  { id: 'hanja_125', char: '育', hun: '기를', eum: '육', pinyin: 'yù',    grade: 7, strokes: 8,  example: '敎育', example_meaning: '교육' },
  { id: 'hanja_126', char: '音', hun: '소리', eum: '음', pinyin: 'yīn',   grade: 7, strokes: 9,  example: '音樂', example_meaning: '음악' },
  { id: 'hanja_127', char: '銀', hun: '은', eum: '은', pinyin: 'yín',     grade: 7, strokes: 14, example: '銀行', example_meaning: '은행' },
  { id: 'hanja_128', char: '入', hun: '들', eum: '입', pinyin: 'rù',      grade: 7, strokes: 2,  example: '入口', example_meaning: '입구' },
  { id: 'hanja_129', char: '作', hun: '지을', eum: '작', pinyin: 'zuò',   grade: 7, strokes: 7,  example: '作文', example_meaning: '작문' },
  { id: 'hanja_130', char: '場', hun: '마당', eum: '장', pinyin: 'chǎng', grade: 7, strokes: 12, example: '市場', example_meaning: '시장' },
  { id: 'hanja_131', char: '全', hun: '온전할', eum: '전', pinyin: 'quán', grade: 7, strokes: 6, example: '全國', example_meaning: '전국' },
  { id: 'hanja_132', char: '電', hun: '번개', eum: '전', pinyin: 'diàn',  grade: 7, strokes: 13, example: '電氣', example_meaning: '전기' },
  { id: 'hanja_133', char: '前', hun: '앞', eum: '전', pinyin: 'qián',    grade: 7, strokes: 9,  example: '前後', example_meaning: '전후' },
  { id: 'hanja_134', char: '祖', hun: '할아비', eum: '조', pinyin: 'zǔ',  grade: 7, strokes: 10, example: '祖國', example_meaning: '조국' },
  { id: 'hanja_135', char: '紙', hun: '종이', eum: '지', pinyin: 'zhǐ',   grade: 7, strokes: 10, example: '色紙', example_meaning: '색지' },
  { id: 'hanja_136', char: '直', hun: '곧을', eum: '직', pinyin: 'zhí',   grade: 7, strokes: 8,  example: '正直', example_meaning: '정직' },
  { id: 'hanja_137', char: '千', hun: '일천', eum: '천', pinyin: 'qiān',  grade: 7, strokes: 3,  example: '千萬', example_meaning: '천만' },
  { id: 'hanja_138', char: '川', hun: '내', eum: '천', pinyin: 'chuān',   grade: 7, strokes: 3,  example: '山川', example_meaning: '산천' },
  { id: 'hanja_139', char: '春', hun: '봄', eum: '춘', pinyin: 'chūn',    grade: 7, strokes: 9,  example: '春秋', example_meaning: '춘추' },
  { id: 'hanja_140', char: '親', hun: '친할', eum: '친', pinyin: 'qīn',   grade: 7, strokes: 16, example: '親舊', example_meaning: '친구' },
  { id: 'hanja_141', char: '他', hun: '다를', eum: '타', pinyin: 'tā',    grade: 7, strokes: 5,  example: '他人', example_meaning: '타인' },
  { id: 'hanja_142', char: '太', hun: '클', eum: '태', pinyin: 'tài',     grade: 7, strokes: 4,  example: '太陽', example_meaning: '태양' },
  { id: 'hanja_143', char: '通', hun: '통할', eum: '통', pinyin: 'tōng',  grade: 7, strokes: 11, example: '交通', example_meaning: '교통' },
  { id: 'hanja_144', char: '平', hun: '평평할', eum: '평', pinyin: 'píng', grade: 7, strokes: 5, example: '平和', example_meaning: '평화' },
  { id: 'hanja_145', char: '韓', hun: '한국', eum: '한', pinyin: 'hán',   grade: 7, strokes: 17, example: '韓國', example_meaning: '한국' },
  { id: 'hanja_146', char: '漢', hun: '한수', eum: '한', pinyin: 'hàn',   grade: 7, strokes: 14, example: '漢字', example_meaning: '한자' },
  { id: 'hanja_147', char: '話', hun: '말씀', eum: '화', pinyin: 'huà',   grade: 7, strokes: 13, example: '電話', example_meaning: '전화' },
  { id: 'hanja_148', char: '黃', hun: '누를', eum: '황', pinyin: 'huáng', grade: 7, strokes: 11, example: '黃金', example_meaning: '황금' },
  { id: 'hanja_149', char: '後', hun: '뒤', eum: '후', pinyin: 'hòu',     grade: 7, strokes: 9,  example: '前後', example_meaning: '전후' },
  { id: 'hanja_150', char: '休', hun: '쉴', eum: '휴', pinyin: 'xiū',     grade: 7, strokes: 6,  example: '休日', example_meaning: '휴일' },
  { id: 'hanja_151', char: '夏', hun: '여름', eum: '하', pinyin: 'xià',   grade: 7, strokes: 10, example: '夏冬', example_meaning: '하동' },
  { id: 'hanja_152', char: '秋', hun: '가을', eum: '추', pinyin: 'qiū',   grade: 7, strokes: 9,  example: '春秋', example_meaning: '춘추' },
  { id: 'hanja_153', char: '元', hun: '으뜸', eum: '원', pinyin: 'yuán',  grade: 7, strokes: 4,  example: '元氣', example_meaning: '원기' },
  // 6급 추가
  { id: 'hanja_154', char: '加', hun: '더할', eum: '가', pinyin: 'jiā',   grade: 6, strokes: 5,  example: '加入', example_meaning: '가입' },
  { id: 'hanja_155', char: '各', hun: '각각', eum: '각', pinyin: 'gè',    grade: 6, strokes: 6,  example: '各自', example_meaning: '각자' },
  { id: 'hanja_156', char: '感', hun: '느낄', eum: '감', pinyin: 'gǎn',   grade: 6, strokes: 13, example: '感動', example_meaning: '감동' },
  { id: 'hanja_157', char: '車', hun: '수레', eum: '차', pinyin: 'chē',   grade: 6, strokes: 7,  example: '汽車', example_meaning: '기차' },
  { id: 'hanja_158', char: '見', hun: '볼', eum: '견', pinyin: 'jiàn',    grade: 6, strokes: 7,  example: '意見', example_meaning: '의견' },
  { id: 'hanja_159', char: '京', hun: '서울', eum: '경', pinyin: 'jīng',  grade: 6, strokes: 8,  example: '上京', example_meaning: '상경' },
  { id: 'hanja_160', char: '交', hun: '사귈', eum: '교', pinyin: 'jiāo',  grade: 6, strokes: 6,  example: '交通', example_meaning: '교통' },
  { id: 'hanja_161', char: '敎', hun: '가르칠', eum: '교', pinyin: 'jiāo', grade: 6, strokes: 11, example: '敎育', example_meaning: '교육' },
  { id: 'hanja_162', char: '區', hun: '구분할', eum: '구', pinyin: 'qū',  grade: 6, strokes: 11, example: '地區', example_meaning: '지구' },
  { id: 'hanja_163', char: '求', hun: '구할', eum: '구', pinyin: 'qiú',   grade: 6, strokes: 7,  example: '要求', example_meaning: '요구' },
  { id: 'hanja_164', char: '軍', hun: '군사', eum: '군', pinyin: 'jūn',   grade: 6, strokes: 9,  example: '軍人', example_meaning: '군인' },
  { id: 'hanja_165', char: '近', hun: '가까울', eum: '근', pinyin: 'jìn', grade: 6, strokes: 8,  example: '近來', example_meaning: '근래' },
  { id: 'hanja_166', char: '急', hun: '급할', eum: '급', pinyin: 'jí',    grade: 6, strokes: 9,  example: '急行', example_meaning: '급행' },
  { id: 'hanja_167', char: '技', hun: '재주', eum: '기', pinyin: 'jì',    grade: 6, strokes: 7,  example: '技術', example_meaning: '기술' },
  { id: 'hanja_168', char: '基', hun: '터', eum: '기', pinyin: 'jī',      grade: 6, strokes: 11, example: '基本', example_meaning: '기본' },
  { id: 'hanja_169', char: '來', hun: '올', eum: '래', pinyin: 'lái',     grade: 6, strokes: 8,  example: '往來', example_meaning: '왕래' },
  { id: 'hanja_170', char: '多', hun: '많을', eum: '다', pinyin: 'duō',   grade: 6, strokes: 6,  example: '多少', example_meaning: '다소' },
  { id: 'hanja_171', char: '短', hun: '짧을', eum: '단', pinyin: 'duǎn',  grade: 6, strokes: 12, example: '長短', example_meaning: '장단' },
  { id: 'hanja_172', char: '當', hun: '마땅', eum: '당', pinyin: 'dāng',  grade: 6, strokes: 13, example: '當然', example_meaning: '당연' },
  { id: 'hanja_173', char: '對', hun: '대할', eum: '대', pinyin: 'duì',   grade: 6, strokes: 14, example: '對話', example_meaning: '대화' },
  { id: 'hanja_174', char: '圖', hun: '그림', eum: '도', pinyin: 'tú',    grade: 6, strokes: 14, example: '地圖', example_meaning: '지도' },
  { id: 'hanja_175', char: '都', hun: '도읍', eum: '도', pinyin: 'dōu',   grade: 6, strokes: 12, example: '首都', example_meaning: '수도' },
  { id: 'hanja_176', char: '等', hun: '무리', eum: '등', pinyin: 'děng',  grade: 6, strokes: 12, example: '等級', example_meaning: '등급' },
  { id: 'hanja_177', char: '樂', hun: '즐길', eum: '락', pinyin: 'lè',    grade: 6, strokes: 15, example: '音樂', example_meaning: '음악' },
  { id: 'hanja_178', char: '量', hun: '헤아릴', eum: '량', pinyin: 'liàng', grade: 6, strokes: 12, example: '力量', example_meaning: '역량' },
  { id: 'hanja_179', char: '旅', hun: '나그네', eum: '려', pinyin: 'lǚ',  grade: 6, strokes: 10, example: '旅行', example_meaning: '여행' },
  { id: 'hanja_180', char: '歷', hun: '지낼', eum: '력', pinyin: 'lì',    grade: 6, strokes: 16, example: '歷史', example_meaning: '역사' },
  { id: 'hanja_181', char: '練', hun: '익힐', eum: '련', pinyin: 'liàn',  grade: 6, strokes: 15, example: '練習', example_meaning: '연습' },
  { id: 'hanja_182', char: '路', hun: '길', eum: '로', pinyin: 'lù',      grade: 6, strokes: 13, example: '道路', example_meaning: '도로' },
  { id: 'hanja_183', char: '流', hun: '흐를', eum: '류', pinyin: 'liú',   grade: 6, strokes: 10, example: '流動', example_meaning: '유동' },
  { id: 'hanja_184', char: '萬', hun: '일만', eum: '만', pinyin: 'wàn',   grade: 6, strokes: 15, example: '萬物', example_meaning: '만물' },
  { id: 'hanja_185', char: '每', hun: '매양', eum: '매', pinyin: 'měi',   grade: 6, strokes: 7,  example: '每日', example_meaning: '매일' },
  { id: 'hanja_186', char: '美', hun: '아름다울', eum: '미', pinyin: 'měi', grade: 6, strokes: 9, example: '美術', example_meaning: '미술' },
  { id: 'hanja_187', char: '反', hun: '돌이킬', eum: '반', pinyin: 'fǎn', grade: 6, strokes: 4,  example: '反省', example_meaning: '반성' },
  { id: 'hanja_188', char: '發', hun: '필', eum: '발', pinyin: 'fā',      grade: 6, strokes: 12, example: '出發', example_meaning: '출발' },
  { id: 'hanja_189', char: '放', hun: '놓을', eum: '방', pinyin: 'fàng',  grade: 6, strokes: 8,  example: '放學', example_meaning: '방학' },
  { id: 'hanja_190', char: '別', hun: '나눌', eum: '별', pinyin: 'bié',   grade: 6, strokes: 7,  example: '別名', example_meaning: '별명' },
  { id: 'hanja_191', char: '病', hun: '병', eum: '병', pinyin: 'bìng',    grade: 6, strokes: 10, example: '病院', example_meaning: '병원' },
  { id: 'hanja_192', char: '步', hun: '걸음', eum: '보', pinyin: 'bù',    grade: 6, strokes: 7,  example: '進步', example_meaning: '진보' },
  { id: 'hanja_193', char: '福', hun: '복', eum: '복', pinyin: 'fú',      grade: 6, strokes: 13, example: '幸福', example_meaning: '행복' },
  { id: 'hanja_194', char: '服', hun: '옷', eum: '복', pinyin: 'fú',      grade: 6, strokes: 8,  example: '衣服', example_meaning: '의복' },
  { id: 'hanja_195', char: '本', hun: '근본', eum: '본', pinyin: 'běn',   grade: 6, strokes: 5,  example: '基本', example_meaning: '기본' },
  { id: 'hanja_196', char: '部', hun: '떼', eum: '부', pinyin: 'bù',      grade: 6, strokes: 11, example: '部分', example_meaning: '부분' },
  { id: 'hanja_197', char: '使', hun: '하여금', eum: '사', pinyin: 'shǐ', grade: 6, strokes: 8,  example: '大使', example_meaning: '대사' },
  { id: 'hanja_198', char: '産', hun: '낳을', eum: '산', pinyin: 'chǎn',  grade: 6, strokes: 11, example: '生産', example_meaning: '생산' },
  { id: 'hanja_199', char: '想', hun: '생각', eum: '상', pinyin: 'xiǎng', grade: 6, strokes: 13, example: '思想', example_meaning: '사상' },
  { id: 'hanja_200', char: '常', hun: '항상', eum: '상', pinyin: 'cháng', grade: 6, strokes: 11, example: '日常', example_meaning: '일상' },
  { id: 'hanja_201', char: '線', hun: '줄', eum: '선', pinyin: 'xiàn',    grade: 6, strokes: 15, example: '直線', example_meaning: '직선' },
  { id: 'hanja_202', char: '說', hun: '말씀', eum: '설', pinyin: 'shuō',  grade: 6, strokes: 14, example: '小說', example_meaning: '소설' },
  { id: 'hanja_203', char: '成', hun: '이룰', eum: '성', pinyin: 'chéng', grade: 6, strokes: 7,  example: '成功', example_meaning: '성공' },
  { id: 'hanja_204', char: '洗', hun: '씻을', eum: '세', pinyin: 'xǐ',    grade: 6, strokes: 9,  example: '洗手', example_meaning: '세수' },
  { id: 'hanja_205', char: '歲', hun: '해', eum: '세', pinyin: 'suì',     grade: 6, strokes: 13, example: '歲月', example_meaning: '세월' },
  { id: 'hanja_206', char: '消', hun: '사라질', eum: '소', pinyin: 'xiāo', grade: 6, strokes: 10, example: '消火', example_meaning: '소화' },
  { id: 'hanja_207', char: '速', hun: '빠를', eum: '속', pinyin: 'sù',    grade: 6, strokes: 11, example: '速度', example_meaning: '속도' },
  { id: 'hanja_208', char: '數', hun: '셀', eum: '수', pinyin: 'shù',     grade: 6, strokes: 15, example: '數學', example_meaning: '수학' },
  { id: 'hanja_209', char: '受', hun: '받을', eum: '수', pinyin: 'shòu',  grade: 6, strokes: 8,  example: '受信', example_meaning: '수신' },
  { id: 'hanja_210', char: '術', hun: '재주', eum: '술', pinyin: 'shù',   grade: 6, strokes: 11, example: '技術', example_meaning: '기술' },
  { id: 'hanja_211', char: '習', hun: '익힐', eum: '습', pinyin: 'xí',    grade: 6, strokes: 11, example: '學習', example_meaning: '학습' },
  { id: 'hanja_212', char: '時', hun: '때', eum: '시', pinyin: 'shí',     grade: 6, strokes: 10, example: '時間', example_meaning: '시간' },
  { id: 'hanja_213', char: '始', hun: '비로소', eum: '시', pinyin: 'shǐ', grade: 6, strokes: 8,  example: '開始', example_meaning: '개시' },
  { id: 'hanja_214', char: '身', hun: '몸', eum: '신', pinyin: 'shēn',    grade: 6, strokes: 7,  example: '自身', example_meaning: '자신' },
  { id: 'hanja_215', char: '新', hun: '새', eum: '신', pinyin: 'xīn',     grade: 6, strokes: 13, example: '新聞', example_meaning: '신문' },
  { id: 'hanja_216', char: '信', hun: '믿을', eum: '신', pinyin: 'xìn',   grade: 6, strokes: 9,  example: '信用', example_meaning: '신용' },
  { id: 'hanja_217', char: '失', hun: '잃을', eum: '실', pinyin: 'shī',   grade: 6, strokes: 5,  example: '失敗', example_meaning: '실패' },
  { id: 'hanja_218', char: '我', hun: '나', eum: '아', pinyin: 'wǒ',      grade: 6, strokes: 7,  example: '自我', example_meaning: '자아' },
  { id: 'hanja_219', char: '愛', hun: '사랑', eum: '애', pinyin: 'ài',    grade: 6, strokes: 13, example: '愛國', example_meaning: '애국' },
  { id: 'hanja_220', char: '野', hun: '들', eum: '야', pinyin: 'yě',      grade: 6, strokes: 11, example: '野外', example_meaning: '야외' },
  { id: 'hanja_221', char: '弱', hun: '약할', eum: '약', pinyin: 'ruò',   grade: 6, strokes: 10, example: '强弱', example_meaning: '강약' },
  { id: 'hanja_222', char: '藥', hun: '약', eum: '약', pinyin: 'yào',     grade: 6, strokes: 19, example: '藥草', example_meaning: '약초' },
  { id: 'hanja_223', char: '陽', hun: '볕', eum: '양', pinyin: 'yáng',    grade: 6, strokes: 12, example: '太陽', example_meaning: '태양' },
  { id: 'hanja_224', char: '養', hun: '기를', eum: '양', pinyin: 'yǎng',  grade: 6, strokes: 15, example: '養育', example_meaning: '양육' },
  { id: 'hanja_225', char: '英', hun: '꽃부리', eum: '영', pinyin: 'yīng', grade: 6, strokes: 9, example: '英語', example_meaning: '영어' },
  { id: 'hanja_226', char: '禮', hun: '예도', eum: '예', pinyin: 'lǐ',    grade: 6, strokes: 18, example: '禮節', example_meaning: '예절' },
  { id: 'hanja_227', char: '溫', hun: '따뜻할', eum: '온', pinyin: 'wēn', grade: 6, strokes: 13, example: '溫度', example_meaning: '온도' },
  { id: 'hanja_228', char: '完', hun: '완전할', eum: '완', pinyin: 'wán', grade: 6, strokes: 7,  example: '完全', example_meaning: '완전' },
  { id: 'hanja_229', char: '要', hun: '요긴할', eum: '요', pinyin: 'yào', grade: 6, strokes: 9,  example: '必要', example_meaning: '필요' },
  { id: 'hanja_230', char: '遠', hun: '멀', eum: '원', pinyin: 'yuǎn',    grade: 6, strokes: 13, example: '遠近', example_meaning: '원근' },
  { id: 'hanja_231', char: '願', hun: '원할', eum: '원', pinyin: 'yuàn',  grade: 6, strokes: 19, example: '所願', example_meaning: '소원' },
  { id: 'hanja_232', char: '位', hun: '자리', eum: '위', pinyin: 'wèi',   grade: 6, strokes: 7,  example: '地位', example_meaning: '지위' },
  { id: 'hanja_233', char: '由', hun: '말미암을', eum: '유', pinyin: 'yóu', grade: 6, strokes: 5, example: '理由', example_meaning: '이유' },
  { id: 'hanja_234', char: '以', hun: '써', eum: '이', pinyin: 'yǐ',      grade: 6, strokes: 5,  example: '以上', example_meaning: '이상' },
  { id: 'hanja_235', char: '因', hun: '인할', eum: '인', pinyin: 'yīn',   grade: 6, strokes: 6,  example: '原因', example_meaning: '원인' },
  { id: 'hanja_236', char: '自', hun: '스스로', eum: '자', pinyin: 'zì',  grade: 6, strokes: 6,  example: '自由', example_meaning: '자유' },
  { id: 'hanja_237', char: '才', hun: '재주', eum: '재', pinyin: 'cái',   grade: 6, strokes: 3,  example: '天才', example_meaning: '천재' },
  { id: 'hanja_238', char: '在', hun: '있을', eum: '재', pinyin: 'zài',   grade: 6, strokes: 6,  example: '現在', example_meaning: '현재' },
  { id: 'hanja_239', char: '戰', hun: '싸울', eum: '전', pinyin: 'zhàn',  grade: 6, strokes: 16, example: '戰爭', example_meaning: '전쟁' },
  { id: 'hanja_240', char: '情', hun: '뜻', eum: '정', pinyin: 'qíng',    grade: 6, strokes: 11, example: '感情', example_meaning: '감정' },
  { id: 'hanja_241', char: '政', hun: '정사', eum: '정', pinyin: 'zhèng', grade: 6, strokes: 9,  example: '政治', example_meaning: '정치' },
  { id: 'hanja_242', char: '早', hun: '이를', eum: '조', pinyin: 'zǎo',   grade: 6, strokes: 6,  example: '早朝', example_meaning: '조조' },
  { id: 'hanja_243', char: '左', hun: '왼', eum: '좌', pinyin: 'zuǒ',     grade: 6, strokes: 5,  example: '左右', example_meaning: '좌우' },
  { id: 'hanja_244', char: '主', hun: '임금', eum: '주', pinyin: 'zhǔ',   grade: 6, strokes: 5,  example: '主人', example_meaning: '주인' },
  { id: 'hanja_245', char: '注', hun: '부을', eum: '주', pinyin: 'zhù',   grade: 6, strokes: 8,  example: '注意', example_meaning: '주의' },
  { id: 'hanja_246', char: '重', hun: '무거울', eum: '중', pinyin: 'zhòng', grade: 6, strokes: 9, example: '重要', example_meaning: '중요' },
  { id: 'hanja_247', char: '知', hun: '알', eum: '지', pinyin: 'zhī',     grade: 6, strokes: 8,  example: '知識', example_meaning: '지식' },
  { id: 'hanja_248', char: '集', hun: '모을', eum: '집', pinyin: 'jí',    grade: 6, strokes: 12, example: '集合', example_meaning: '집합' },
  { id: 'hanja_249', char: '次', hun: '버금', eum: '차', pinyin: 'cì',    grade: 6, strokes: 6,  example: '次第', example_meaning: '차제' },
  { id: 'hanja_250', char: '請', hun: '청할', eum: '청', pinyin: 'qǐng',  grade: 6, strokes: 15, example: '請求', example_meaning: '청구' },
  { id: 'hanja_251', char: '體', hun: '몸', eum: '체', pinyin: 'tǐ',      grade: 6, strokes: 23, example: '體力', example_meaning: '체력' },
  { id: 'hanja_252', char: '初', hun: '처음', eum: '초', pinyin: 'chū',   grade: 6, strokes: 7,  example: '最初', example_meaning: '최초' },
  { id: 'hanja_253', char: '最', hun: '가장', eum: '최', pinyin: 'zuì',   grade: 6, strokes: 12, example: '最高', example_meaning: '최고' },
  { id: 'hanja_254', char: '出', hun: '날', eum: '출', pinyin: 'chū',     grade: 6, strokes: 5,  example: '出口', example_meaning: '출구' },
  { id: 'hanja_255', char: '治', hun: '다스릴', eum: '치', pinyin: 'zhì', grade: 6, strokes: 8,  example: '政治', example_meaning: '정치' },
  { id: 'hanja_256', char: '特', hun: '특별할', eum: '특', pinyin: 'tè',  grade: 6, strokes: 10, example: '特別', example_meaning: '특별' },
  { id: 'hanja_257', char: '合', hun: '합할', eum: '합', pinyin: 'hé',    grade: 6, strokes: 6,  example: '合格', example_meaning: '합격' },
  { id: 'hanja_258', char: '行', hun: '다닐', eum: '행', pinyin: 'xíng',  grade: 6, strokes: 6,  example: '行動', example_meaning: '행동' },
  { id: 'hanja_259', char: '向', hun: '향할', eum: '향', pinyin: 'xiàng', grade: 6, strokes: 6,  example: '方向', example_meaning: '방향' },
  { id: 'hanja_260', char: '現', hun: '나타날', eum: '현', pinyin: 'xiàn', grade: 6, strokes: 11, example: '現在', example_meaning: '현재' },
  { id: 'hanja_261', char: '好', hun: '좋을', eum: '호', pinyin: 'hǎo',   grade: 6, strokes: 6,  example: '好意', example_meaning: '호의' },
  { id: 'hanja_262', char: '化', hun: '될', eum: '화', pinyin: 'huà',     grade: 6, strokes: 4,  example: '文化', example_meaning: '문화' },
  { id: 'hanja_263', char: '確', hun: '굳을', eum: '확', pinyin: 'què',   grade: 6, strokes: 15, example: '確認', example_meaning: '확인' },
  { id: 'hanja_264', char: '活', hun: '살', eum: '활', pinyin: 'huó',     grade: 6, strokes: 9,  example: '生活', example_meaning: '생활' },
  { id: 'hanja_265', char: '會', hun: '모일', eum: '회', pinyin: 'huì',   grade: 6, strokes: 13, example: '社會', example_meaning: '사회' },
  // 5급 추가
  { id: 'hanja_266', char: '價', hun: '값', eum: '가', pinyin: 'jià',     grade: 5, strokes: 15, example: '物價', example_meaning: '물가' },
  { id: 'hanja_267', char: '可', hun: '옳을', eum: '가', pinyin: 'kě',    grade: 5, strokes: 5,  example: '可能', example_meaning: '가능' },
  { id: 'hanja_268', char: '減', hun: '덜', eum: '감', pinyin: 'jiǎn',    grade: 5, strokes: 12, example: '減少', example_meaning: '감소' },
  { id: 'hanja_269', char: '講', hun: '강론할', eum: '강', pinyin: 'jiǎng', grade: 5, strokes: 17, example: '講義', example_meaning: '강의' },
  { id: 'hanja_270', char: '去', hun: '갈', eum: '거', pinyin: 'qù',      grade: 5, strokes: 5,  example: '去來', example_meaning: '거래' },
  { id: 'hanja_271', char: '建', hun: '세울', eum: '건', pinyin: 'jiàn',  grade: 5, strokes: 9,  example: '建設', example_meaning: '건설' },
  { id: 'hanja_272', char: '決', hun: '결단할', eum: '결', pinyin: 'jué', grade: 5, strokes: 7,  example: '決定', example_meaning: '결정' },
  { id: 'hanja_273', char: '敬', hun: '공경', eum: '경', pinyin: 'jìng',  grade: 5, strokes: 13, example: '尊敬', example_meaning: '존경' },
  { id: 'hanja_274', char: '輕', hun: '가벼울', eum: '경', pinyin: 'qīng', grade: 5, strokes: 14, example: '輕重', example_meaning: '경중' },
  { id: 'hanja_275', char: '景', hun: '경치', eum: '경', pinyin: 'jǐng',  grade: 5, strokes: 12, example: '景色', example_meaning: '경색' },
  { id: 'hanja_276', char: '界', hun: '지경', eum: '계', pinyin: 'jiè',   grade: 5, strokes: 9,  example: '世界', example_meaning: '세계' },
  { id: 'hanja_277', char: '計', hun: '셈할', eum: '계', pinyin: 'jì',    grade: 5, strokes: 9,  example: '計算', example_meaning: '계산' },
  { id: 'hanja_278', char: '苦', hun: '쓸', eum: '고', pinyin: 'kǔ',      grade: 5, strokes: 9,  example: '苦生', example_meaning: '고생' },
  { id: 'hanja_279', char: '告', hun: '고할', eum: '고', pinyin: 'gào',   grade: 5, strokes: 7,  example: '廣告', example_meaning: '광고' },
  { id: 'hanja_280', char: '功', hun: '공', eum: '공', pinyin: 'gōng',    grade: 5, strokes: 5,  example: '成功', example_meaning: '성공' },
  { id: 'hanja_281', char: '科', hun: '과목', eum: '과', pinyin: 'kē',    grade: 5, strokes: 9,  example: '科學', example_meaning: '과학' },
  { id: 'hanja_282', char: '果', hun: '과실', eum: '과', pinyin: 'guǒ',   grade: 5, strokes: 8,  example: '結果', example_meaning: '결과' },
  { id: 'hanja_283', char: '觀', hun: '볼', eum: '관', pinyin: 'guān',    grade: 5, strokes: 25, example: '觀光', example_meaning: '관광' },
  { id: 'hanja_284', char: '廣', hun: '넓을', eum: '광', pinyin: 'guǎng', grade: 5, strokes: 14, example: '廣告', example_meaning: '광고' },
  { id: 'hanja_285', char: '光', hun: '빛', eum: '광', pinyin: 'guāng',   grade: 5, strokes: 6,  example: '光明', example_meaning: '광명' },
  { id: 'hanja_286', char: '救', hun: '구원할', eum: '구', pinyin: 'jiù', grade: 5, strokes: 11, example: '救助', example_meaning: '구조' },
  { id: 'hanja_287', char: '權', hun: '권세', eum: '권', pinyin: 'quán',  grade: 5, strokes: 22, example: '人權', example_meaning: '인권' },
  { id: 'hanja_288', char: '規', hun: '법', eum: '규', pinyin: 'guī',     grade: 5, strokes: 11, example: '規則', example_meaning: '규칙' },
  { id: 'hanja_289', char: '根', hun: '뿌리', eum: '근', pinyin: 'gēn',   grade: 5, strokes: 10, example: '根本', example_meaning: '근본' },
  { id: 'hanja_290', char: '禁', hun: '금할', eum: '금', pinyin: 'jìn',   grade: 5, strokes: 13, example: '禁止', example_meaning: '금지' },
  { id: 'hanja_291', char: '給', hun: '줄', eum: '급', pinyin: 'gěi',     grade: 5, strokes: 12, example: '給食', example_meaning: '급식' },
  { id: 'hanja_292', char: '難', hun: '어려울', eum: '난', pinyin: 'nán', grade: 5, strokes: 19, example: '困難', example_meaning: '곤난' },
  { id: 'hanja_293', char: '念', hun: '생각할', eum: '념', pinyin: 'niàn', grade: 5, strokes: 8, example: '記念', example_meaning: '기념' },
  { id: 'hanja_294', char: '能', hun: '능할', eum: '능', pinyin: 'néng',  grade: 5, strokes: 10, example: '可能', example_meaning: '가능' },
  { id: 'hanja_295', char: '德', hun: '덕', eum: '덕', pinyin: 'dé',      grade: 5, strokes: 15, example: '道德', example_meaning: '도덕' },
  { id: 'hanja_296', char: '獨', hun: '홀로', eum: '독', pinyin: 'dú',    grade: 5, strokes: 16, example: '獨立', example_meaning: '독립' },
  { id: 'hanja_297', char: '得', hun: '얻을', eum: '득', pinyin: 'dé',    grade: 5, strokes: 11, example: '取得', example_meaning: '취득' },
  { id: 'hanja_298', char: '老', hun: '늙을', eum: '로', pinyin: 'lǎo',   grade: 5, strokes: 6,  example: '老人', example_meaning: '노인' },
  { id: 'hanja_299', char: '類', hun: '무리', eum: '류', pinyin: 'lèi',   grade: 5, strokes: 19, example: '人類', example_meaning: '인류' },
  { id: 'hanja_300', char: '利', hun: '이로울', eum: '리', pinyin: 'lì',  grade: 5, strokes: 7,  example: '利益', example_meaning: '이익' },
  { id: 'hanja_301', char: '立', hun: '설', eum: '립', pinyin: 'lì',      grade: 5, strokes: 5,  example: '獨立', example_meaning: '독립' },
  { id: 'hanja_302', char: '望', hun: '바랄', eum: '망', pinyin: 'wàng',  grade: 5, strokes: 11, example: '希望', example_meaning: '희망' },
  { id: 'hanja_303', char: '買', hun: '살', eum: '매', pinyin: 'mǎi',     grade: 5, strokes: 12, example: '買入', example_meaning: '매입' },
  { id: 'hanja_304', char: '賣', hun: '팔', eum: '매', pinyin: 'mài',     grade: 5, strokes: 15, example: '賣出', example_meaning: '매출' },
  { id: 'hanja_305', char: '武', hun: '호반', eum: '무', pinyin: 'wǔ',    grade: 5, strokes: 8,  example: '武力', example_meaning: '무력' },
  { id: 'hanja_306', char: '無', hun: '없을', eum: '무', pinyin: 'wú',    grade: 5, strokes: 12, example: '無限', example_meaning: '무한' },
  { id: 'hanja_307', char: '米', hun: '쌀', eum: '미', pinyin: 'mǐ',      grade: 5, strokes: 6,  example: '白米', example_meaning: '백미' },
  { id: 'hanja_308', char: '班', hun: '나눌', eum: '반', pinyin: 'bān',   grade: 5, strokes: 10, example: '班長', example_meaning: '반장' },
  { id: 'hanja_309', char: '倍', hun: '배', eum: '배', pinyin: 'bèi',     grade: 5, strokes: 10, example: '倍數', example_meaning: '배수' },
  { id: 'hanja_310', char: '變', hun: '변할', eum: '변', pinyin: 'biàn',  grade: 5, strokes: 23, example: '變化', example_meaning: '변화' },
  { id: 'hanja_311', char: '保', hun: '지킬', eum: '보', pinyin: 'bǎo',   grade: 5, strokes: 9,  example: '保護', example_meaning: '보호' },
  { id: 'hanja_312', char: '報', hun: '갚을', eum: '보', pinyin: 'bào',   grade: 5, strokes: 12, example: '報告', example_meaning: '보고' },
  { id: 'hanja_313', char: '富', hun: '부유할', eum: '부', pinyin: 'fù',  grade: 5, strokes: 12, example: '富强', example_meaning: '부강' },
  { id: 'hanja_314', char: '死', hun: '죽을', eum: '사', pinyin: 'sǐ',    grade: 5, strokes: 6,  example: '死亡', example_meaning: '사망' },
  { id: 'hanja_315', char: '森', hun: '수풀', eum: '삼', pinyin: 'sēn',   grade: 5, strokes: 12, example: '森林', example_meaning: '삼림' },
  { id: 'hanja_316', char: '相', hun: '서로', eum: '상', pinyin: 'xiāng', grade: 5, strokes: 9,  example: '相互', example_meaning: '상호' },
  { id: 'hanja_317', char: '商', hun: '장사', eum: '상', pinyin: 'shāng', grade: 5, strokes: 11, example: '商業', example_meaning: '상업' },
  { id: 'hanja_318', char: '設', hun: '베풀', eum: '설', pinyin: 'shè',   grade: 5, strokes: 11, example: '設立', example_meaning: '설립' },
  { id: 'hanja_319', char: '聲', hun: '소리', eum: '성', pinyin: 'shēng', grade: 5, strokes: 17, example: '聲音', example_meaning: '성음' },
  { id: 'hanja_320', char: '省', hun: '살필', eum: '성', pinyin: 'shěng', grade: 5, strokes: 9,  example: '反省', example_meaning: '반성' },
  { id: 'hanja_321', char: '孫', hun: '손자', eum: '손', pinyin: 'sūn',   grade: 5, strokes: 10, example: '子孫', example_meaning: '자손' },
  { id: 'hanja_322', char: '首', hun: '머리', eum: '수', pinyin: 'shǒu',  grade: 5, strokes: 9,  example: '首都', example_meaning: '수도' },
  { id: 'hanja_323', char: '守', hun: '지킬', eum: '수', pinyin: 'shǒu',  grade: 5, strokes: 6,  example: '守護', example_meaning: '수호' },
  { id: 'hanja_324', char: '視', hun: '볼', eum: '시', pinyin: 'shì',     grade: 5, strokes: 11, example: '注視', example_meaning: '주시' },
  { id: 'hanja_325', char: '詩', hun: '시', eum: '시', pinyin: 'shī',     grade: 5, strokes: 13, example: '詩人', example_meaning: '시인' },
  { id: 'hanja_326', char: '識', hun: '알', eum: '식', pinyin: 'shí',     grade: 5, strokes: 19, example: '知識', example_meaning: '지식' },
  { id: 'hanja_327', char: '實', hun: '열매', eum: '실', pinyin: 'shí',   grade: 5, strokes: 14, example: '實力', example_meaning: '실력' },
  { id: 'hanja_328', char: '兒', hun: '아이', eum: '아', pinyin: 'ér',    grade: 5, strokes: 8,  example: '兒童', example_meaning: '아동' },
  { id: 'hanja_329', char: '若', hun: '같을', eum: '약', pinyin: 'ruò',   grade: 5, strokes: 8,  example: '若干', example_meaning: '약간' },
  { id: 'hanja_330', char: '嚴', hun: '엄할', eum: '엄', pinyin: 'yán',   grade: 5, strokes: 20, example: '嚴格', example_meaning: '엄격' },
  { id: 'hanja_331', char: '如', hun: '같을', eum: '여', pinyin: 'rú',    grade: 5, strokes: 6,  example: '如何', example_meaning: '여하' },
  { id: 'hanja_332', char: '逆', hun: '거스를', eum: '역', pinyin: 'nì',  grade: 5, strokes: 9,  example: '逆順', example_meaning: '역순' },
  { id: 'hanja_333', char: '連', hun: '이을', eum: '연', pinyin: 'lián',  grade: 5, strokes: 11, example: '連結', example_meaning: '연결' },
  { id: 'hanja_334', char: '榮', hun: '영화', eum: '영', pinyin: 'róng',  grade: 5, strokes: 14, example: '榮光', example_meaning: '영광' },
  { id: 'hanja_335', char: '藝', hun: '재주', eum: '예', pinyin: 'yì',    grade: 5, strokes: 19, example: '技藝', example_meaning: '기예' },
  { id: 'hanja_336', char: '往', hun: '갈', eum: '왕', pinyin: 'wǎng',    grade: 5, strokes: 8,  example: '往來', example_meaning: '왕래' },
  { id: 'hanja_337', char: '欲', hun: '하고자할', eum: '욕', pinyin: 'yù', grade: 5, strokes: 11, example: '食欲', example_meaning: '식욕' },
  { id: 'hanja_338', char: '員', hun: '인원', eum: '원', pinyin: 'yuán',  grade: 5, strokes: 10, example: '人員', example_meaning: '인원' },
  { id: 'hanja_339', char: '爲', hun: '할', eum: '위', pinyin: 'wéi',     grade: 5, strokes: 12, example: '行爲', example_meaning: '행위' },
  { id: 'hanja_340', char: '遊', hun: '놀', eum: '유', pinyin: 'yóu',     grade: 5, strokes: 13, example: '遊動', example_meaning: '유동' },
  { id: 'hanja_341', char: '律', hun: '법칙', eum: '율', pinyin: 'lǜ',    grade: 5, strokes: 9,  example: '法律', example_meaning: '법률' },
  { id: 'hanja_342', char: '義', hun: '옳을', eum: '의', pinyin: 'yì',    grade: 5, strokes: 13, example: '正義', example_meaning: '정의' },
  { id: 'hanja_343', char: '移', hun: '옮길', eum: '이', pinyin: 'yí',    grade: 5, strokes: 11, example: '移動', example_meaning: '이동' },
  { id: 'hanja_344', char: '仁', hun: '어질', eum: '인', pinyin: 'rén',   grade: 5, strokes: 4,  example: '仁義', example_meaning: '인의' },
  { id: 'hanja_345', char: '引', hun: '끌', eum: '인', pinyin: 'yǐn',     grade: 5, strokes: 4,  example: '引用', example_meaning: '인용' },
  { id: 'hanja_346', char: '任', hun: '맡길', eum: '임', pinyin: 'rèn',   grade: 5, strokes: 6,  example: '任務', example_meaning: '임무' },
  { id: 'hanja_347', char: '資', hun: '재물', eum: '자', pinyin: 'zī',    grade: 5, strokes: 13, example: '資料', example_meaning: '자료' },
  { id: 'hanja_348', char: '將', hun: '장수', eum: '장', pinyin: 'jiāng', grade: 5, strokes: 11, example: '將軍', example_meaning: '장군' },
  { id: 'hanja_349', char: '的', hun: '과녁', eum: '적', pinyin: 'de',    grade: 5, strokes: 8,  example: '目的', example_meaning: '목적' },
  { id: 'hanja_350', char: '典', hun: '법', eum: '전', pinyin: 'diǎn',    grade: 5, strokes: 8,  example: '古典', example_meaning: '고전' },
  { id: 'hanja_351', char: '節', hun: '마디', eum: '절', pinyin: 'jié',   grade: 5, strokes: 15, example: '禮節', example_meaning: '예절' },
  { id: 'hanja_352', char: '點', hun: '점', eum: '점', pinyin: 'diǎn',    grade: 5, strokes: 17, example: '地點', example_meaning: '지점' },
  { id: 'hanja_353', char: '定', hun: '정할', eum: '정', pinyin: 'dìng',  grade: 5, strokes: 8,  example: '決定', example_meaning: '결정' },
  { id: 'hanja_354', char: '照', hun: '비출', eum: '조', pinyin: 'zhào',  grade: 5, strokes: 13, example: '照明', example_meaning: '조명' },
  { id: 'hanja_355', char: '族', hun: '겨레', eum: '족', pinyin: 'zú',    grade: 5, strokes: 11, example: '民族', example_meaning: '민족' },
  { id: 'hanja_356', char: '終', hun: '마칠', eum: '종', pinyin: 'zhōng', grade: 5, strokes: 11, example: '終日', example_meaning: '종일' },
  { id: 'hanja_357', char: '周', hun: '두루', eum: '주', pinyin: 'zhōu',  grade: 5, strokes: 8,  example: '周邊', example_meaning: '주변' },
  { id: 'hanja_358', char: '準', hun: '준할', eum: '준', pinyin: 'zhǔn',  grade: 5, strokes: 13, example: '基準', example_meaning: '기준' },
  { id: 'hanja_359', char: '至', hun: '이를', eum: '지', pinyin: 'zhì',   grade: 5, strokes: 6,  example: '至今', example_meaning: '지금' },
  { id: 'hanja_360', char: '進', hun: '나아갈', eum: '진', pinyin: 'jìn', grade: 5, strokes: 12, example: '前進', example_meaning: '전진' },
  { id: 'hanja_361', char: '差', hun: '다를', eum: '차', pinyin: 'chā',   grade: 5, strokes: 10, example: '差異', example_meaning: '차이' },
  { id: 'hanja_362', char: '創', hun: '비롯할', eum: '창', pinyin: 'chuàng', grade: 5, strokes: 12, example: '創造', example_meaning: '창조' },
  { id: 'hanja_363', char: '處', hun: '곳', eum: '처', pinyin: 'chǔ',     grade: 5, strokes: 11, example: '處理', example_meaning: '처리' },
  { id: 'hanja_364', char: '聽', hun: '들을', eum: '청', pinyin: 'tīng',  grade: 5, strokes: 22, example: '聽音', example_meaning: '청음' },
  { id: 'hanja_365', char: '超', hun: '뛰어넘을', eum: '초', pinyin: 'chāo', grade: 5, strokes: 12, example: '超過', example_meaning: '초과' },
  { id: 'hanja_366', char: '總', hun: '거느릴', eum: '총', pinyin: 'zǒng', grade: 5, strokes: 17, example: '總合', example_meaning: '총합' },
  { id: 'hanja_367', char: '推', hun: '밀', eum: '추', pinyin: 'tuī',     grade: 5, strokes: 11, example: '推進', example_meaning: '추진' },
  { id: 'hanja_368', char: '取', hun: '가질', eum: '취', pinyin: 'qǔ',    grade: 5, strokes: 8,  example: '取得', example_meaning: '취득' },
  { id: 'hanja_369', char: '探', hun: '찾을', eum: '탐', pinyin: 'tàn',   grade: 5, strokes: 11, example: '探求', example_meaning: '탐구' },
  { id: 'hanja_370', char: '統', hun: '거느릴', eum: '통', pinyin: 'tǒng', grade: 5, strokes: 12, example: '統一', example_meaning: '통일' },
  { id: 'hanja_371', char: '破', hun: '깨뜨릴', eum: '파', pinyin: 'pò',  grade: 5, strokes: 10, example: '破壞', example_meaning: '파괴' },
  { id: 'hanja_372', char: '敗', hun: '패할', eum: '패', pinyin: 'bài',   grade: 5, strokes: 11, example: '失敗', example_meaning: '실패' },
  { id: 'hanja_373', char: '便', hun: '편할', eum: '편', pinyin: 'biàn',  grade: 5, strokes: 9,  example: '便利', example_meaning: '편리' },
  { id: 'hanja_374', char: '表', hun: '겉', eum: '표', pinyin: 'biǎo',    grade: 5, strokes: 8,  example: '表現', example_meaning: '표현' },
  { id: 'hanja_375', char: '標', hun: '표할', eum: '표', pinyin: 'biāo',  grade: 5, strokes: 15, example: '目標', example_meaning: '목표' },
  { id: 'hanja_376', char: '必', hun: '반드시', eum: '필', pinyin: 'bì',  grade: 5, strokes: 5,  example: '必要', example_meaning: '필요' },
  { id: 'hanja_377', char: '筆', hun: '붓', eum: '필', pinyin: 'bǐ',      grade: 5, strokes: 12, example: '鉛筆', example_meaning: '연필' },
  { id: 'hanja_378', char: '限', hun: '한할', eum: '한', pinyin: 'xiàn',  grade: 5, strokes: 9,  example: '限界', example_meaning: '한계' },
  { id: 'hanja_379', char: '解', hun: '풀', eum: '해', pinyin: 'jiě',     grade: 5, strokes: 13, example: '解決', example_meaning: '해결' },
  { id: 'hanja_380', char: '幸', hun: '다행', eum: '행', pinyin: 'xìng',  grade: 5, strokes: 8,  example: '幸福', example_meaning: '행복' },
  { id: 'hanja_381', char: '許', hun: '허락할', eum: '허', pinyin: 'xǔ',  grade: 5, strokes: 11, example: '許可', example_meaning: '허가' },
  { id: 'hanja_382', char: '血', hun: '피', eum: '혈', pinyin: 'xuè',     grade: 5, strokes: 6,  example: '血液', example_meaning: '혈액' },
  { id: 'hanja_383', char: '號', hun: '이름', eum: '호', pinyin: 'hào',   grade: 5, strokes: 13, example: '信號', example_meaning: '신호' },
  { id: 'hanja_384', char: '和', hun: '화할', eum: '화', pinyin: 'hé',    grade: 5, strokes: 8,  example: '平和', example_meaning: '평화' },
  { id: 'hanja_385', char: '換', hun: '바꿀', eum: '환', pinyin: 'huàn',  grade: 5, strokes: 12, example: '交換', example_meaning: '교환' },
  { id: 'hanja_386', char: '孝', hun: '효도', eum: '효', pinyin: 'xiào',  grade: 5, strokes: 7,  example: '孝道', example_meaning: '효도' },
  { id: 'hanja_387', char: '興', hun: '일어날', eum: '흥', pinyin: 'xīng', grade: 5, strokes: 16, example: '興味', example_meaning: '흥미' },
  { id: 'hanja_388', char: '希', hun: '바랄', eum: '희', pinyin: 'xī',    grade: 5, strokes: 7,  example: '希望', example_meaning: '희망' },
];

const STAGES = [
  { id: 1, grade: 8, words: ['hanja_001','hanja_002','hanja_003','hanja_004','hanja_005','hanja_006','hanja_007','hanja_008','hanja_009','hanja_010'] },
  { id: 2, grade: 8, words: ['hanja_011','hanja_012','hanja_013','hanja_014','hanja_015','hanja_016','hanja_017','hanja_018','hanja_019','hanja_020'] },
  { id: 3, grade: 8, words: ['hanja_021','hanja_022','hanja_023','hanja_024','hanja_025','hanja_026','hanja_027','hanja_028','hanja_029','hanja_030'] },
  { id: 4, grade: 8, words: ['hanja_031','hanja_032','hanja_033','hanja_034','hanja_035','hanja_036','hanja_037','hanja_038','hanja_039','hanja_040'] },
  { id: 5, grade: 8, words: ['hanja_041','hanja_042','hanja_043','hanja_044','hanja_045','hanja_046','hanja_047','hanja_048','hanja_049','hanja_050'] },
  { id: 6, grade: 8, words: ['hanja_051','hanja_052','hanja_053','hanja_054','hanja_055','hanja_056','hanja_057','hanja_058','hanja_059','hanja_060'] },
  { id: 7, grade: 7, words: ['hanja_061','hanja_062','hanja_063','hanja_064','hanja_065','hanja_066','hanja_067','hanja_068','hanja_069','hanja_070'] },
  { id: 8,  grade: 7, words: ['hanja_071','hanja_072','hanja_073','hanja_074','hanja_075','hanja_076','hanja_077','hanja_078','hanja_079','hanja_080'] },
  { id: 9,  grade: 7, words: ['hanja_081','hanja_082','hanja_083','hanja_084','hanja_085','hanja_086','hanja_087','hanja_088','hanja_089','hanja_090'] },
  { id: 10, grade: 7, words: ['hanja_091','hanja_092','hanja_093','hanja_094','hanja_095','hanja_096','hanja_097','hanja_098','hanja_099','hanja_100'] },
  { id: 11, grade: 7, words: ['hanja_101','hanja_102','hanja_103','hanja_104','hanja_105','hanja_106','hanja_107','hanja_108','hanja_109','hanja_110'] },
  { id: 12, grade: 7, words: ['hanja_111','hanja_112','hanja_113','hanja_114','hanja_115','hanja_116','hanja_117','hanja_118','hanja_119','hanja_120'] },
  { id: 13, grade: 7, words: ['hanja_121','hanja_122','hanja_123','hanja_124','hanja_125','hanja_126','hanja_127','hanja_128','hanja_129','hanja_130'] },
  { id: 14, grade: 7, words: ['hanja_131','hanja_132','hanja_133','hanja_134','hanja_135','hanja_136','hanja_137','hanja_138','hanja_139','hanja_140'] },
  { id: 15, grade: 7, words: ['hanja_141','hanja_142','hanja_143','hanja_144','hanja_145','hanja_146','hanja_147','hanja_148','hanja_149','hanja_150'] },
  { id: 16, grade: 7, words: ['hanja_151','hanja_152','hanja_153','hanja_076','hanja_086','hanja_096','hanja_106','hanja_116','hanja_126','hanja_136'] },
  { id: 17, grade: 6, words: ['hanja_154','hanja_155','hanja_156','hanja_157','hanja_158','hanja_159','hanja_160','hanja_161','hanja_162','hanja_163'] },
  { id: 18, grade: 6, words: ['hanja_164','hanja_165','hanja_166','hanja_167','hanja_168','hanja_169','hanja_170','hanja_171','hanja_172','hanja_173'] },
  { id: 19, grade: 6, words: ['hanja_174','hanja_175','hanja_176','hanja_177','hanja_178','hanja_179','hanja_180','hanja_181','hanja_182','hanja_183'] },
  { id: 20, grade: 6, words: ['hanja_184','hanja_185','hanja_186','hanja_187','hanja_188','hanja_189','hanja_190','hanja_191','hanja_192','hanja_193'] },
  { id: 21, grade: 6, words: ['hanja_194','hanja_195','hanja_196','hanja_197','hanja_198','hanja_199','hanja_200','hanja_201','hanja_202','hanja_203'] },
  { id: 22, grade: 6, words: ['hanja_204','hanja_205','hanja_206','hanja_207','hanja_208','hanja_209','hanja_210','hanja_211','hanja_212','hanja_213'] },
  { id: 23, grade: 6, words: ['hanja_214','hanja_215','hanja_216','hanja_217','hanja_218','hanja_219','hanja_220','hanja_221','hanja_222','hanja_223'] },
  { id: 24, grade: 6, words: ['hanja_224','hanja_225','hanja_226','hanja_227','hanja_228','hanja_229','hanja_230','hanja_231','hanja_232','hanja_233'] },
  { id: 25, grade: 6, words: ['hanja_234','hanja_235','hanja_236','hanja_237','hanja_238','hanja_239','hanja_240','hanja_241','hanja_242','hanja_243'] },
  { id: 26, grade: 6, words: ['hanja_244','hanja_245','hanja_246','hanja_247','hanja_248','hanja_249','hanja_250','hanja_251','hanja_252','hanja_253'] },
  { id: 27, grade: 6, words: ['hanja_254','hanja_255','hanja_256','hanja_257','hanja_258','hanja_259','hanja_260','hanja_261','hanja_262','hanja_263'] },
  { id: 28, grade: 6, words: ['hanja_264','hanja_265','hanja_154','hanja_164','hanja_174','hanja_184','hanja_194','hanja_204','hanja_214','hanja_224'] },
  { id: 29, grade: 5, words: ['hanja_266','hanja_267','hanja_268','hanja_269','hanja_270','hanja_271','hanja_272','hanja_273','hanja_274','hanja_275'] },
  { id: 30, grade: 5, words: ['hanja_276','hanja_277','hanja_278','hanja_279','hanja_280','hanja_281','hanja_282','hanja_283','hanja_284','hanja_285'] },
  { id: 31, grade: 5, words: ['hanja_286','hanja_287','hanja_288','hanja_289','hanja_290','hanja_291','hanja_292','hanja_293','hanja_294','hanja_295'] },
  { id: 32, grade: 5, words: ['hanja_296','hanja_297','hanja_298','hanja_299','hanja_300','hanja_301','hanja_302','hanja_303','hanja_304','hanja_305'] },
  { id: 33, grade: 5, words: ['hanja_306','hanja_307','hanja_308','hanja_309','hanja_310','hanja_311','hanja_312','hanja_313','hanja_314','hanja_315'] },
  { id: 34, grade: 5, words: ['hanja_316','hanja_317','hanja_318','hanja_319','hanja_320','hanja_321','hanja_322','hanja_323','hanja_324','hanja_325'] },
  { id: 35, grade: 5, words: ['hanja_326','hanja_327','hanja_328','hanja_329','hanja_330','hanja_331','hanja_332','hanja_333','hanja_334','hanja_335'] },
  { id: 36, grade: 5, words: ['hanja_336','hanja_337','hanja_338','hanja_339','hanja_340','hanja_341','hanja_342','hanja_343','hanja_344','hanja_345'] },
  { id: 37, grade: 5, words: ['hanja_346','hanja_347','hanja_348','hanja_349','hanja_350','hanja_351','hanja_352','hanja_353','hanja_354','hanja_355'] },
  { id: 38, grade: 5, words: ['hanja_356','hanja_357','hanja_358','hanja_359','hanja_360','hanja_361','hanja_362','hanja_363','hanja_364','hanja_365'] },
  { id: 39, grade: 5, words: ['hanja_366','hanja_367','hanja_368','hanja_369','hanja_370','hanja_371','hanja_372','hanja_373','hanja_374','hanja_375'] },
  { id: 40, grade: 5, words: ['hanja_376','hanja_377','hanja_378','hanja_379','hanja_380','hanja_381','hanja_382','hanja_383','hanja_384','hanja_385'] },
  { id: 41, grade: 5, words: ['hanja_386','hanja_387','hanja_388','hanja_266','hanja_276','hanja_286','hanja_296','hanja_306','hanja_316','hanja_326'] },
];
