const HANJA_DATA = [
  // 8급 — 숫자
  { id: 'hanja_001', char: '一', hun: '한', eum: '일', pinyin: 'yī',    grade: 8, strokes: 1,  example: '一月', example_meaning: '일월' },
  { id: 'hanja_002', char: '二', hun: '두', eum: '이', pinyin: 'èr',    grade: 8, strokes: 2,  example: '二月', example_meaning: '이월' },
  { id: 'hanja_003', char: '三', hun: '석', eum: '삼', pinyin: 'sān',   grade: 8, strokes: 3,  example: '三月', example_meaning: '삼월' },
  { id: 'hanja_004', char: '四', hun: '넉', eum: '사', pinyin: 'sì',    grade: 8, strokes: 5,  example: '四月', example_meaning: '사월' },
  { id: 'hanja_005', char: '五', hun: '다섯', eum: '오', pinyin: 'wǔ', grade: 8, strokes: 4,  example: '五月', example_meaning: '오월' },
  { id: 'hanja_006', char: '六', hun: '여섯', eum: '육', pinyin: 'liù', grade: 8, strokes: 4,  example: '六月', example_meaning: '유월' },
  { id: 'hanja_007', char: '七', hun: '일곱', eum: '칠', pinyin: 'qī', grade: 8, strokes: 2,  example: '七月', example_meaning: '칠월' },
  { id: 'hanja_008', char: '八', hun: '여덟', eum: '팔', pinyin: 'bā', grade: 8, strokes: 2,  example: '八月', example_meaning: '팔월' },
  { id: 'hanja_009', char: '九', hun: '아홉', eum: '구', pinyin: 'jiǔ', grade: 8, strokes: 2,  example: '九月', example_meaning: '구월' },
  { id: 'hanja_010', char: '十', hun: '열', eum: '십', pinyin: 'shí',  grade: 8, strokes: 2,  example: '十月', example_meaning: '시월' },
  // 8급 — 자연
  { id: 'hanja_011', char: '山', hun: '뫼', eum: '산', pinyin: 'shān',  grade: 8, strokes: 3,  example: '山水', example_meaning: '산수' },
  { id: 'hanja_012', char: '水', hun: '물', eum: '수', pinyin: 'shuǐ', grade: 8, strokes: 4,  example: '水力', example_meaning: '수력' },
  { id: 'hanja_013', char: '火', hun: '불', eum: '화', pinyin: 'huǒ',  grade: 8, strokes: 4,  example: '火山', example_meaning: '화산' },
  { id: 'hanja_014', char: '木', hun: '나무', eum: '목', pinyin: 'mù', grade: 8, strokes: 4,  example: '木手', example_meaning: '목수' },
  { id: 'hanja_015', char: '金', hun: '쇠', eum: '금', pinyin: 'jīn',  grade: 8, strokes: 8,  example: '金山', example_meaning: '금산' },
  { id: 'hanja_016', char: '土', hun: '흙', eum: '토', pinyin: 'tǔ',   grade: 8, strokes: 3,  example: '土地', example_meaning: '토지' },
  { id: 'hanja_017', char: '日', hun: '날', eum: '일', pinyin: 'rì',   grade: 8, strokes: 4,  example: '日月', example_meaning: '일월' },
  { id: 'hanja_018', char: '月', hun: '달', eum: '월', pinyin: 'yuè',  grade: 8, strokes: 4,  example: '月光', example_meaning: '월광' },
  { id: 'hanja_019', char: '天', hun: '하늘', eum: '천', pinyin: 'tiān', grade: 8, strokes: 4, example: '天下', example_meaning: '천하' },
  { id: 'hanja_020', char: '地', hun: '땅', eum: '지', pinyin: 'dì',   grade: 8, strokes: 6,  example: '地下', example_meaning: '지하' },
  // 8급 — 방향
  { id: 'hanja_021', char: '東', hun: '동녘', eum: '동', pinyin: 'dōng', grade: 8, strokes: 8, example: '東西', example_meaning: '동서' },
  { id: 'hanja_022', char: '西', hun: '서녘', eum: '서', pinyin: 'xī',  grade: 8, strokes: 6,  example: '東西', example_meaning: '동서' },
  { id: 'hanja_023', char: '南', hun: '남녘', eum: '남', pinyin: 'nán', grade: 8, strokes: 9,  example: '南北', example_meaning: '남북' },
  { id: 'hanja_024', char: '北', hun: '북녘', eum: '북', pinyin: 'běi', grade: 8, strokes: 5,  example: '南北', example_meaning: '남북' },
  // 8급 — 가족
  { id: 'hanja_025', char: '父', hun: '아비', eum: '부', pinyin: 'fù',   grade: 8, strokes: 4, example: '父母', example_meaning: '부모' },
  { id: 'hanja_026', char: '母', hun: '어미', eum: '모', pinyin: 'mǔ',   grade: 8, strokes: 5, example: '父母', example_meaning: '부모' },
  { id: 'hanja_027', char: '兄', hun: '형', eum: '형', pinyin: 'xiōng', grade: 8, strokes: 5,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_028', char: '弟', hun: '아우', eum: '제', pinyin: 'dì',  grade: 8, strokes: 7,  example: '兄弟', example_meaning: '형제' },
  { id: 'hanja_029', char: '子', hun: '아들', eum: '자', pinyin: 'zǐ',  grade: 8, strokes: 3,  example: '子女', example_meaning: '자녀' },
  { id: 'hanja_030', char: '女', hun: '계집', eum: '녀', pinyin: 'nǚ',  grade: 8, strokes: 3,  example: '女子', example_meaning: '여자' },
  // 8급 — 학교·나라
  { id: 'hanja_031', char: '學', hun: '배울', eum: '학', pinyin: 'xué', grade: 8, strokes: 16, example: '學校', example_meaning: '학교' },
  { id: 'hanja_032', char: '校', hun: '학교', eum: '교', pinyin: 'xiào', grade: 8, strokes: 10, example: '學校', example_meaning: '학교' },
  { id: 'hanja_033', char: '國', hun: '나라', eum: '국', pinyin: 'guó', grade: 8, strokes: 11, example: '國土', example_meaning: '국토' },
  { id: 'hanja_034', char: '王', hun: '임금', eum: '왕', pinyin: 'wáng', grade: 8, strokes: 4, example: '王子', example_meaning: '왕자' },
  { id: 'hanja_035', char: '民', hun: '백성', eum: '민', pinyin: 'mín', grade: 8, strokes: 5,  example: '國民', example_meaning: '국민' },
  // 8급 — 신체·사람
  { id: 'hanja_036', char: '人', hun: '사람', eum: '인', pinyin: 'rén', grade: 8, strokes: 2,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_037', char: '口', hun: '입', eum: '구', pinyin: 'kǒu',   grade: 8, strokes: 3,  example: '人口', example_meaning: '인구' },
  { id: 'hanja_038', char: '手', hun: '손', eum: '수', pinyin: 'shǒu',  grade: 8, strokes: 4,  example: '手足', example_meaning: '수족' },
  { id: 'hanja_039', char: '目', hun: '눈', eum: '목', pinyin: 'mù',   grade: 8, strokes: 5,  example: '目前', example_meaning: '목전' },
  { id: 'hanja_040', char: '耳', hun: '귀', eum: '이', pinyin: 'ěr',   grade: 8, strokes: 6,  example: '耳目', example_meaning: '이목' },
  // 8급 — 크기·위치
  { id: 'hanja_041', char: '大', hun: '큰', eum: '대', pinyin: 'dà',    grade: 8, strokes: 3,  example: '大小', example_meaning: '대소' },
  { id: 'hanja_042', char: '小', hun: '작을', eum: '소', pinyin: 'xiǎo', grade: 8, strokes: 3, example: '大小', example_meaning: '대소' },
  { id: 'hanja_043', char: '上', hun: '위', eum: '상', pinyin: 'shàng', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_044', char: '下', hun: '아래', eum: '하', pinyin: 'xià', grade: 8, strokes: 3,  example: '上下', example_meaning: '상하' },
  { id: 'hanja_045', char: '中', hun: '가운데', eum: '중', pinyin: 'zhōng', grade: 8, strokes: 4, example: '中間', example_meaning: '중간' },
  { id: 'hanja_046', char: '外', hun: '바깥', eum: '외', pinyin: 'wài', grade: 8, strokes: 5,  example: '外國', example_meaning: '외국' },
  { id: 'hanja_047', char: '內', hun: '안', eum: '내', pinyin: 'nèi',   grade: 8, strokes: 4,  example: '國內', example_meaning: '국내' },
  // 8급 — 시간·생명
  { id: 'hanja_048', char: '年', hun: '해', eum: '년', pinyin: 'nián',  grade: 8, strokes: 6,  example: '年月', example_meaning: '연월' },
  { id: 'hanja_049', char: '先', hun: '먼저', eum: '선', pinyin: 'xiān', grade: 8, strokes: 6, example: '先生', example_meaning: '선생' },
  { id: 'hanja_050', char: '生', hun: '날', eum: '생', pinyin: 'shēng', grade: 8, strokes: 5,  example: '先生', example_meaning: '선생' },
  // 8급 — 색·형용
  { id: 'hanja_051', char: '白', hun: '흰', eum: '백', pinyin: 'bái',   grade: 8, strokes: 5,  example: '白色', example_meaning: '백색' },
  { id: 'hanja_052', char: '靑', hun: '푸를', eum: '청', pinyin: 'qīng', grade: 8, strokes: 8, example: '靑年', example_meaning: '청년' },
  { id: 'hanja_053', char: '長', hun: '길', eum: '장', pinyin: 'cháng', grade: 8, strokes: 8,  example: '長短', example_meaning: '장단' },
  { id: 'hanja_054', char: '正', hun: '바를', eum: '정', pinyin: 'zhèng', grade: 8, strokes: 5, example: '正直', example_meaning: '정직' },
  // 7급 입문 (stage 6+)
  { id: 'hanja_055', char: '力', hun: '힘', eum: '력', pinyin: 'lì',    grade: 7, strokes: 2,  example: '力道', example_meaning: '역도' },
  { id: 'hanja_056', char: '文', hun: '글', eum: '문', pinyin: 'wén',   grade: 7, strokes: 4,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_057', char: '字', hun: '글자', eum: '자', pinyin: 'zì',  grade: 7, strokes: 6,  example: '文字', example_meaning: '문자' },
  { id: 'hanja_058', char: '門', hun: '문', eum: '문', pinyin: 'mén',   grade: 7, strokes: 8,  example: '門前', example_meaning: '문전' },
  { id: 'hanja_059', char: '里', hun: '마을', eum: '리', pinyin: 'lǐ',  grade: 7, strokes: 7,  example: '里長', example_meaning: '이장' },
  { id: 'hanja_060', char: '花', hun: '꽃', eum: '화', pinyin: 'huā',   grade: 7, strokes: 7,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_061', char: '草', hun: '풀', eum: '초', pinyin: 'cǎo',   grade: 7, strokes: 9,  example: '花草', example_meaning: '화초' },
  { id: 'hanja_062', char: '林', hun: '수풀', eum: '림', pinyin: 'lín', grade: 7, strokes: 8,  example: '山林', example_meaning: '산림' },
  { id: 'hanja_063', char: '江', hun: '강', eum: '강', pinyin: 'jiāng', grade: 7, strokes: 6,  example: '江山', example_meaning: '강산' },
  { id: 'hanja_064', char: '海', hun: '바다', eum: '해', pinyin: 'hǎi', grade: 7, strokes: 9,  example: '海外', example_meaning: '해외' },
  { id: 'hanja_065', char: '風', hun: '바람', eum: '풍', pinyin: 'fēng', grade: 7, strokes: 9, example: '風水', example_meaning: '풍수' },
  { id: 'hanja_066', char: '石', hun: '돌', eum: '석', pinyin: 'shí',   grade: 7, strokes: 5,  example: '石山', example_meaning: '석산' },
  { id: 'hanja_067', char: '心', hun: '마음', eum: '심', pinyin: 'xīn', grade: 7, strokes: 4,  example: '心中', example_meaning: '심중' },
  { id: 'hanja_068', char: '食', hun: '먹을', eum: '식', pinyin: 'shí', grade: 7, strokes: 9,  example: '食水', example_meaning: '식수' },
  { id: 'hanja_069', char: '道', hun: '길', eum: '도', pinyin: 'dào',   grade: 7, strokes: 12, example: '道路', example_meaning: '도로' },
  { id: 'hanja_070', char: '家', hun: '집', eum: '가', pinyin: 'jiā',   grade: 7, strokes: 10, example: '家門', example_meaning: '가문' },
  { id: 'hanja_071', char: '工', hun: '장인', eum: '공', pinyin: 'gōng', grade: 7, strokes: 3, example: '工人', example_meaning: '공인' },
  { id: 'hanja_072', char: '市', hun: '시장', eum: '시', pinyin: 'shì', grade: 7, strokes: 5,  example: '市場', example_meaning: '시장' },
  { id: 'hanja_073', char: '村', hun: '마을', eum: '촌', pinyin: 'cūn', grade: 7, strokes: 7,  example: '山村', example_meaning: '산촌' },
  { id: 'hanja_074', char: '空', hun: '빌', eum: '공', pinyin: 'kōng', grade: 7, strokes: 8,   example: '空中', example_meaning: '공중' },
  { id: 'hanja_075', char: '足', hun: '발', eum: '족', pinyin: 'zú',    grade: 7, strokes: 7,  example: '手足', example_meaning: '수족' },
];

const STAGES = [
  { id: 1, grade: 8, words: ['hanja_001','hanja_002','hanja_003','hanja_004','hanja_005','hanja_006','hanja_007','hanja_008','hanja_009','hanja_010'] },
  { id: 2, grade: 8, words: ['hanja_011','hanja_012','hanja_013','hanja_014','hanja_015','hanja_016','hanja_017','hanja_018','hanja_019','hanja_020'] },
  { id: 3, grade: 8, words: ['hanja_021','hanja_022','hanja_023','hanja_024','hanja_025','hanja_026','hanja_027','hanja_028','hanja_029','hanja_030'] },
  { id: 4, grade: 8, words: ['hanja_031','hanja_032','hanja_033','hanja_034','hanja_035','hanja_036','hanja_037','hanja_038','hanja_039','hanja_040'] },
  { id: 5, grade: 8, words: ['hanja_041','hanja_042','hanja_043','hanja_044','hanja_045','hanja_046','hanja_047','hanja_048','hanja_049','hanja_050'] },
  { id: 6, grade: 8, words: ['hanja_051','hanja_052','hanja_053','hanja_054','hanja_055','hanja_056','hanja_057','hanja_058','hanja_059','hanja_060'] },
  { id: 7, grade: 7, words: ['hanja_061','hanja_062','hanja_063','hanja_064','hanja_065','hanja_066','hanja_067','hanja_068','hanja_069','hanja_070'] },
  { id: 8, grade: 7, words: ['hanja_071','hanja_072','hanja_073','hanja_074','hanja_075','hanja_001','hanja_011','hanja_021','hanja_031','hanja_041'] },
];
